export type MutationMatrixStatus = 'complete' | 'partial' | 'missing';

export interface OwnerConsoleMutationMatrixEntry {
  workspace: 'Governance' | 'Experience' | 'Commerce' | 'Community Ops';
  feature: string;
  uiRoute: string;
  uiAction: string;
  apiEndpoint: string;
  requiredPermission: string;
  positivePersona: string;
  negativePersona: string;
  status: MutationMatrixStatus;
  notes: string;
}

export const OWNER_CONSOLE_MUTATION_MATRIX: OwnerConsoleMutationMatrixEntry[] = [
  {
    workspace: 'Governance',
    feature: 'User role assignment',
    uiRoute: '/dashboard/users',
    uiAction: 'Assign a role to a selected profile.',
    apiEndpoint: 'POST /api/permissions/assignment',
    requiredPermission: 'users.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes:
      'Users management now supports assign-role mutations through the owner-console modal.',
  },
  {
    workspace: 'Governance',
    feature: 'User role unassignment',
    uiRoute: '/dashboard/users',
    uiAction: 'Remove an existing role assignment from a selected profile.',
    apiEndpoint: 'DELETE /api/permissions/assignment/:assignmentId',
    requiredPermission: 'users.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes:
      'Users management now supports unassign-role mutations through the owner-console modal.',
  },
  {
    workspace: 'Governance',
    feature: 'Role create',
    uiRoute: '/dashboard/roles',
    uiAction: 'Create a new role.',
    apiEndpoint: 'POST /api/permissions/role',
    requiredPermission: 'roles.create',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'Role creation is implemented in the roles management workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'Role update',
    uiRoute: '/dashboard/roles',
    uiAction: 'Edit an existing role.',
    apiEndpoint: 'PUT /api/permissions/role/:id',
    requiredPermission: 'roles.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'Role editing is implemented in the roles management workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'Role delete',
    uiRoute: '/dashboard/roles',
    uiAction: 'Delete an existing role.',
    apiEndpoint: 'DELETE /api/permissions/role/:id',
    requiredPermission: 'roles.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'Role deletion is implemented in the roles management workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'Role permission add',
    uiRoute: '/dashboard/roles',
    uiAction: 'Attach a permission to a role.',
    apiEndpoint: 'POST /api/permissions/role/:roleId/permission/:permissionId',
    requiredPermission: 'roles.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The service and protected endpoint exist, but the owner-console does not expose a UI flow for modifying role permissions.',
  },
  {
    workspace: 'Governance',
    feature: 'Role permission remove',
    uiRoute: '/dashboard/roles',
    uiAction: 'Detach a permission from a role.',
    apiEndpoint: 'DELETE /api/permissions/role/:roleId/permission/:permissionId',
    requiredPermission: 'roles.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The service and protected endpoint exist, but the owner-console does not expose a UI flow for modifying role permissions.',
  },
  {
    workspace: 'Governance',
    feature: 'Permission create',
    uiRoute: '/dashboard/permissions',
    uiAction: 'Create a new permission.',
    apiEndpoint: 'POST /api/permissions/permission',
    requiredPermission: 'permissions.create',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'Permission creation is implemented in the permissions management workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'Permission update',
    uiRoute: '/dashboard/permissions',
    uiAction: 'Edit an existing permission.',
    apiEndpoint: 'PUT /api/permissions/permission/:id',
    requiredPermission: 'permissions.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'Permission editing is implemented in the permissions management workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'Permission delete',
    uiRoute: '/dashboard/permissions',
    uiAction: 'Delete an existing permission.',
    apiEndpoint: 'DELETE /api/permissions/permission/:id',
    requiredPermission: 'permissions.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'Permission deletion is implemented in the permissions management workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'App scope create',
    uiRoute: '/dashboard/app-scopes',
    uiAction: 'Create a new app scope.',
    apiEndpoint: 'POST /api/permissions/app-scope',
    requiredPermission: 'appscopes.create',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'App scope creation is implemented in the app scopes workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'App scope update',
    uiRoute: '/dashboard/app-scopes',
    uiAction: 'Edit an existing app scope.',
    apiEndpoint: 'PUT /api/permissions/app-scope/:id',
    requiredPermission: 'appscopes.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'App scope editing is implemented in the app scopes workspace.',
  },
  {
    workspace: 'Governance',
    feature: 'App scope delete',
    uiRoute: '/dashboard/app-scopes',
    uiAction: 'Delete an existing app scope.',
    apiEndpoint: 'DELETE /api/permissions/app-scope/:id',
    requiredPermission: 'appscopes.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'App scope deletion is implemented in the app scopes workspace.',
  },
  {
    workspace: 'Experience',
    feature: 'App configuration create',
    uiRoute: '/dashboard/app-config',
    uiAction: 'Create a new app configuration.',
    apiEndpoint: 'POST /api/app-config',
    requiredPermission: 'app-config.create',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'The app configuration list and designer both support configuration creation.',
  },
  {
    workspace: 'Experience',
    feature: 'App configuration update',
    uiRoute: '/dashboard/app-config/designer/:id',
    uiAction: 'Edit and save an existing app configuration.',
    apiEndpoint: 'PUT /api/app-config/:id',
    requiredPermission: 'app-config.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'The app configuration designer supports editing existing configurations.',
  },
  {
    workspace: 'Experience',
    feature: 'App configuration delete',
    uiRoute: '/dashboard/app-config',
    uiAction: 'Delete an existing app configuration.',
    apiEndpoint: 'DELETE /api/app-config/:id',
    requiredPermission: 'app-config.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'complete',
    notes: 'The app configuration list supports delete with a direct backend mutation.',
  },
  {
    workspace: 'Experience',
    feature: 'Theme persistence',
    uiRoute: '/dashboard/theme',
    uiAction: 'Save a theme change for platform-controlled applications.',
    apiEndpoint: 'Not implemented',
    requiredPermission: 'Not implemented',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The theme workspace is still a proof of concept and does not persist mutations through a backend service.',
  },
  {
    workspace: 'Commerce',
    feature: 'Product create',
    uiRoute: '/dashboard/store/products',
    uiAction: 'Create a new product.',
    apiEndpoint: 'POST /api/store/products',
    requiredPermission: 'store.product.create',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Product creation is implemented and protected by explicit store permissions.',
  },
  {
    workspace: 'Commerce',
    feature: 'Product update',
    uiRoute: '/dashboard/store/products',
    uiAction: 'Edit an existing product.',
    apiEndpoint: 'PUT /api/store/products/:id',
    requiredPermission: 'store.product.update',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Product editing is implemented and protected by explicit store permissions.',
  },
  {
    workspace: 'Commerce',
    feature: 'Product delete',
    uiRoute: '/dashboard/store/products',
    uiAction: 'Delete an existing product.',
    apiEndpoint: 'DELETE /api/store/products/:id',
    requiredPermission: 'store.product.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Product deletion is implemented and protected by explicit store permissions.',
  },
  {
    workspace: 'Commerce',
    feature: 'Order status update',
    uiRoute: '/dashboard/store/orders',
    uiAction: 'Change an order status.',
    apiEndpoint: 'PUT /api/store/orders/:id',
    requiredPermission: 'store.order.update',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Order status changes are surfaced in the order management workspace.',
  },
  {
    workspace: 'Commerce',
    feature: 'Subscription cancel',
    uiRoute: '/dashboard/store/overview',
    uiAction: 'Cancel an active subscription.',
    apiEndpoint: 'PUT /api/store/subscriptions/:id/cancel',
    requiredPermission: 'store.subscription.cancel',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Subscription cancellation is exposed in the store overview workspace.',
  },
  {
    workspace: 'Commerce',
    feature: 'Appointment approve',
    uiRoute: '/dashboard/store/appointments',
    uiAction: 'Approve a pending appointment.',
    apiEndpoint: 'PUT /api/store/appointments/:id/approve',
    requiredPermission: 'store.appointment.approve',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Appointment approval is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Appointment deny',
    uiRoute: '/dashboard/store/appointments',
    uiAction: 'Deny a pending appointment.',
    apiEndpoint: 'PUT /api/store/appointments/:id/deny',
    requiredPermission: 'store.appointment.deny',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Appointment denial is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Appointment cancel',
    uiRoute: '/dashboard/store/appointments',
    uiAction: 'Cancel an appointment.',
    apiEndpoint: 'PUT /api/store/appointments/:id/cancel',
    requiredPermission: 'store.appointment.cancel',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Appointment cancellation is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Appointment complete',
    uiRoute: '/dashboard/store/appointments',
    uiAction: 'Complete an appointment.',
    apiEndpoint: 'PUT /api/store/appointments/:id/complete',
    requiredPermission: 'store.appointment.complete',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Appointment completion is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Appointment invoice',
    uiRoute: '/dashboard/store/appointments',
    uiAction: 'Generate an invoice for an appointment.',
    apiEndpoint: 'POST /api/store/appointments/:id/invoice',
    requiredPermission: 'store.appointment.invoice',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Invoice generation is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Availability create',
    uiRoute: '/dashboard/store/availability',
    uiAction: 'Create a new availability window.',
    apiEndpoint: 'POST /api/store/availabilities',
    requiredPermission: 'store.availability.create',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Availability creation is implemented and now derives owner identity from the auth token.',
  },
  {
    workspace: 'Commerce',
    feature: 'Availability update',
    uiRoute: '/dashboard/store/availability',
    uiAction: 'Edit an existing availability window.',
    apiEndpoint: 'PUT /api/store/availabilities/:id',
    requiredPermission: 'store.availability.update',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Availability editing is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Availability delete',
    uiRoute: '/dashboard/store/availability',
    uiAction: 'Delete an availability window.',
    apiEndpoint: 'DELETE /api/store/availabilities/:id',
    requiredPermission: 'store.availability.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'complete',
    notes: 'Availability deletion is implemented and permission-protected.',
  },
  {
    workspace: 'Commerce',
    feature: 'Resource create',
    uiRoute: '/dashboard/commerce',
    uiAction: 'Create a bookable resource.',
    apiEndpoint: 'POST /api/store/resources',
    requiredPermission: 'store.resource.create',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'missing',
    notes:
      'The store service and gateway expose resource mutations, but the owner-console has no route or UI for them.',
  },
  {
    workspace: 'Commerce',
    feature: 'Resource update',
    uiRoute: '/dashboard/commerce',
    uiAction: 'Edit a bookable resource.',
    apiEndpoint: 'PUT /api/store/resources/:id',
    requiredPermission: 'store.resource.update',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'missing',
    notes:
      'The store service and gateway expose resource mutations, but the owner-console has no route or UI for them.',
  },
  {
    workspace: 'Commerce',
    feature: 'Resource delete',
    uiRoute: '/dashboard/commerce',
    uiAction: 'Delete a bookable resource.',
    apiEndpoint: 'DELETE /api/store/resources/:id',
    requiredPermission: 'store.resource.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'domain_operator_limited',
    status: 'missing',
    notes:
      'The store service and gateway expose resource mutations, but the owner-console has no route or UI for them.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community create',
    uiRoute: '/dashboard/communities',
    uiAction: 'Create a new community.',
    apiEndpoint: 'POST /api/communities',
    requiredPermission: 'community.create',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The owner-console exposes this flow, but the gateway route is still protected by authentication only instead of explicit permissions.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community update',
    uiRoute: '/dashboard/communities/:id',
    uiAction: 'Edit a community.',
    apiEndpoint: 'PUT /api/communities/:id',
    requiredPermission: 'community.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The owner-console exposes this flow, but the gateway route is still protected by authentication only instead of explicit permissions.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community delete',
    uiRoute: '/dashboard/communities',
    uiAction: 'Delete a community.',
    apiEndpoint: 'DELETE /api/communities/:id',
    requiredPermission: 'community.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The owner-console exposes this flow, but the gateway route is still protected by authentication only instead of explicit permissions.',
  },
  {
    workspace: 'Community Ops',
    feature: 'City create',
    uiRoute: '/dashboard/cities',
    uiAction: 'Create a new city locality record.',
    apiEndpoint: 'POST /api/communities',
    requiredPermission: 'community.create',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'City management uses the community mutation API, which is currently auth-only at the gateway layer.',
  },
  {
    workspace: 'Community Ops',
    feature: 'City update',
    uiRoute: '/dashboard/cities/:id',
    uiAction: 'Edit an existing city locality record.',
    apiEndpoint: 'PUT /api/communities/:id',
    requiredPermission: 'community.update',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'City management uses the community mutation API, which is currently auth-only at the gateway layer.',
  },
  {
    workspace: 'Community Ops',
    feature: 'City delete',
    uiRoute: '/dashboard/cities',
    uiAction: 'Delete an existing city locality record.',
    apiEndpoint: 'DELETE /api/communities/:id',
    requiredPermission: 'community.delete',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'City management uses the community mutation API, which is currently auth-only at the gateway layer.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community member invite',
    uiRoute: '/dashboard/communities/:id/members',
    uiAction: 'Invite a member to a community.',
    apiEndpoint: 'POST /api/communities/:id/members/invite',
    requiredPermission: 'community.invite',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The owner-console exposes this flow, but the gateway route is still protected by authentication only instead of explicit permissions.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community member role update',
    uiRoute: '/dashboard/communities/:id/members',
    uiAction: 'Change a member role.',
    apiEndpoint: 'PUT /api/communities/:id/members/:memberId/role',
    requiredPermission: 'community.manage',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The owner-console exposes this flow, but the gateway route is still protected by authentication only instead of explicit permissions.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community member remove',
    uiRoute: '/dashboard/communities/:id/members',
    uiAction: 'Remove a member from a community.',
    apiEndpoint: 'DELETE /api/communities/:id/members/:memberId',
    requiredPermission: 'community.manage',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'partial',
    notes:
      'The owner-console exposes this flow, but the gateway route is still protected by authentication only instead of explicit permissions.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community manager appoint',
    uiRoute: '/dashboard/communities/:id/members',
    uiAction: 'Appoint a community manager.',
    apiEndpoint: 'POST /api/communities/:id/manager',
    requiredPermission: 'community.manage',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'missing',
    notes:
      'The backend supports manager appointment, but the owner-console does not surface a manager assignment workflow.',
  },
  {
    workspace: 'Community Ops',
    feature: 'Community manager revoke',
    uiRoute: '/dashboard/communities/:id/members',
    uiAction: 'Revoke a community manager.',
    apiEndpoint: 'DELETE /api/communities/:id/manager',
    requiredPermission: 'community.manage',
    positivePersona: 'platform_owner',
    negativePersona: 'operator_readonly',
    status: 'missing',
    notes:
      'The backend supports manager revocation, but the owner-console does not surface a manager assignment workflow.',
  },
];
