import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Generated by `nx run compliance-audit:typeorm:migration:generate` against a
 * database carrying the initial migration, then corrected twice:
 *
 *  1. The generated `DROP INDEX "IDX_compliance_audit_logs_tenant_chain"` is
 *     removed from both directions. That index was created by the initial
 *     migration and is not declared on the entity, so the CLI sees it as an
 *     unmanaged extra and offers to drop it. Dropping it would remove the index
 *     the audit ledger's per-tenant chain reads rely on.
 *
 *  2. Row level security is added, which is the point of the table and which
 *     TypeORM cannot infer: the policy is not expressible in entity metadata.
 *     It matches the `compliance_audit_logs` policy exactly, so a read that
 *     forgets the tenant predicate returns nothing instead of returning another
 *     tenant's documents.
 */
export class VaultDocSchema1790347292239 implements MigrationInterface {
  name = 'VaultDocSchema1790347292239';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "vault_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying(128) NOT NULL, "documentId" character varying(128) NOT NULL, "fileName" character varying(255) NOT NULL, "mimeType" character varying(64) NOT NULL, "kind" character varying(32) NOT NULL DEFAULT 'other', "documentHash" character varying(64) NOT NULL, "contentText" text NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_09a35822af7006cf4e1e934503b" PRIMARY KEY ("id"))`
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "IDX_vault_documents_tenant_document" ON "vault_documents" ("tenantId", "documentId") `
    );
    await queryRunner.query(
      `ALTER TABLE "vault_documents" ENABLE ROW LEVEL SECURITY`
    );
    await queryRunner.query(
      `ALTER TABLE "vault_documents" FORCE ROW LEVEL SECURITY`
    );
    await queryRunner.query(
      `CREATE POLICY "vault_documents_tenant_isolation" ON "vault_documents" USING ("tenantId" = current_setting('app.current_tenant_id', true)) WITH CHECK ("tenantId" = current_setting('app.current_tenant_id', true))`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP POLICY "vault_documents_tenant_isolation" ON "vault_documents"`
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_vault_documents_tenant_document"`
    );
    await queryRunner.query(`DROP TABLE "vault_documents"`);
  }
}
