// GENERATED by tools/mobile/generate-capacitor.mjs from the app registry — do not edit by hand.
export const APP_ENV = {
  mobile: true,
  apiBaseUrl: 'https://fin-commander.experiments.christopherrutherford.net/api',
  socketUrl: 'https://fin-commander.experiments.christopherrutherford.net',
  socketPath: '/socket.io',
};
