import {
    Lead,
    LeadDiscoverySource,
    LeadSource,
    LeadStatus,
    LeadStats,
    LeadTopicDiscoveryIntent,
    Topic,
} from './leads.types';

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000);

export const DUMMY_LEADS: Lead[] = [
    {
        id: 'lead-001',
        name: 'Sarah Chen',
        company: 'TechNova Solutions',
        email: 'sarah.chen@technova.io',
        phone: '+1 (415) 555-0142',
        source: LeadSource.CLUTCH,
        status: LeadStatus.QUALIFIED,
        value: 12500,
        notes: 'CTO looking for React/Node modernization of legacy portal. Budget approved for Q2.',
        nextFollowUp: daysAgo(-2).toISOString(),
        isAutoDiscovered: true,
        searchKeywords: ['react', 'node', 'modernization'],
        createdAt: daysAgo(14),
        updatedAt: daysAgo(3),
    },
    {
        id: 'lead-002',
        name: 'Marcus Williams',
        company: 'GreenPath Consulting',
        email: 'mwilliams@greenpath.co',
        phone: '+1 (312) 555-0198',
        source: LeadSource.REFERRAL,
        status: LeadStatus.PROPOSAL,
        value: 8750,
        notes: 'Referred by James K. Needs a client portal with reporting dashboard. Prefers Angular.',
        nextFollowUp: daysAgo(-1).toISOString(),
        isAutoDiscovered: false,
        createdAt: daysAgo(21),
        updatedAt: daysAgo(5),
    },
    {
        id: 'lead-003',
        name: 'Priya Patel',
        company: 'NexGen Health',
        email: 'priya@nexgenhealth.com',
        source: LeadSource.REMOTE_OK,
        status: LeadStatus.NEW,
        value: 4200,
        notes: 'Posted job for HIPAA-compliant patient onboarding flow. 2-week sprint.',
        isAutoDiscovered: true,
        searchKeywords: ['healthcare', 'HIPAA', 'patient portal'],
        createdAt: daysAgo(2),
        updatedAt: daysAgo(2),
    },
    {
        id: 'lead-004',
        name: 'David Kowalski',
        company: 'Ironclad Manufacturing',
        email: 'dkowalski@ironclad-mfg.com',
        phone: '+1 (614) 555-0277',
        source: LeadSource.COLD,
        status: LeadStatus.CONTACTED,
        value: 18000,
        notes: 'VP of Operations. Reached out about ERP integration and inventory dashboard.',
        nextFollowUp: daysAgo(0).toISOString(),
        isAutoDiscovered: false,
        createdAt: daysAgo(10),
        updatedAt: daysAgo(7),
    },
    {
        id: 'lead-005',
        name: 'Amara Okafor',
        company: 'Bloom & Branch Studio',
        email: 'amara@bloomandbranch.design',
        source: LeadSource.CRUNCHBASE,
        status: LeadStatus.NEGOTIATION,
        value: 6400,
        notes: 'Design agency needs dev partner for e-commerce builds. Recurring project potential.',
        nextFollowUp: daysAgo(-3).toISOString(),
        isAutoDiscovered: true,
        searchKeywords: ['e-commerce', 'shopify', 'headless CMS'],
        createdAt: daysAgo(30),
        updatedAt: daysAgo(4),
    },
    {
        id: 'lead-006',
        name: 'Tom Brennan',
        company: 'ClearView Analytics',
        email: 'tbrennan@clearview-analytics.com',
        phone: '+1 (206) 555-0133',
        source: LeadSource.WE_WORK_REMOTELY,
        status: LeadStatus.WON,
        value: 15000,
        notes: 'Data visualization dashboard project. Signed SOW last week. Kick-off Monday.',
        isAutoDiscovered: true,
        searchKeywords: ['data visualization', 'dashboard', 'D3'],
        createdAt: daysAgo(45),
        updatedAt: daysAgo(7),
    },
    {
        id: 'lead-007',
        name: 'Rachel Nguyen',
        company: 'Peridot Ventures',
        email: 'rachel.n@peridotvc.com',
        source: LeadSource.REFERRAL,
        status: LeadStatus.LOST,
        value: 22000,
        notes: 'Went with in-house team. Keep relationship warm for future portfolio company needs.',
        isAutoDiscovered: false,
        createdAt: daysAgo(60),
        updatedAt: daysAgo(15),
        isFlagged: false,
    },
    {
        id: 'lead-008',
        name: 'Jamal Henderson',
        company: 'UrbanPulse Media',
        email: 'jamal@urbanpulse.media',
        phone: '+1 (646) 555-0188',
        source: LeadSource.GOOGLE_MAPS,
        status: LeadStatus.NEW,
        value: 3500,
        notes: 'Local media startup. Needs a CMS-driven blog and podcast platform.',
        isAutoDiscovered: false,
        createdAt: daysAgo(1),
        updatedAt: daysAgo(1),
    },
    {
        id: 'lead-009',
        name: 'Elena Vasquez',
        company: 'SilverLine Logistics',
        email: 'evasquez@silverlinelogistics.com',
        phone: '+1 (713) 555-0265',
        source: LeadSource.COLD,
        status: LeadStatus.QUALIFIED,
        value: 28000,
        notes: 'Fleet management SaaS. Want to migrate from Angular.js to modern Angular. Large codebase.',
        nextFollowUp: daysAgo(-5).toISOString(),
        isAutoDiscovered: true,
        searchKeywords: ['angular', 'migration', 'SaaS', 'fleet management'],
        createdAt: daysAgo(18),
        updatedAt: daysAgo(6),
    },
    {
        id: 'lead-010',
        name: 'Chris Abernathy',
        company: 'Bright Spark Education',
        email: 'cabernathy@brightspark.edu',
        source: LeadSource.HIMALAYAS,
        status: LeadStatus.CONTACTED,
        value: 7800,
        notes: 'EdTech startup building LMS platform. Looking for full-stack contractor.',
        nextFollowUp: daysAgo(1).toISOString(),
        isAutoDiscovered: true,
        searchKeywords: ['edtech', 'LMS', 'full-stack'],
        createdAt: daysAgo(8),
        updatedAt: daysAgo(3),
    },
    {
        id: 'lead-011',
        name: 'Kenji Yamamoto',
        company: 'AeroSync',
        email: 'kenji@aerosync.jp',
        source: LeadSource.JOBICY,
        status: LeadStatus.PROPOSAL,
        value: 9500,
        notes: 'IoT dashboard for drone fleet monitoring. WebSocket real-time data. 6-week timeline.',
        nextFollowUp: daysAgo(-1).toISOString(),
        isAutoDiscovered: true,
        searchKeywords: ['IoT', 'dashboard', 'real-time', 'WebSocket'],
        createdAt: daysAgo(12),
        updatedAt: daysAgo(2),
    },
    {
        id: 'lead-012',
        name: 'Lisa Moreau',
        company: 'Ciel Patisserie',
        email: 'lisa@cielpatisserie.com',
        phone: '+1 (504) 555-0321',
        source: LeadSource.GOOGLE_MAPS,
        status: LeadStatus.WON,
        value: 2800,
        notes: 'Local bakery chain. Online ordering system with Stripe integration. Simple build.',
        isAutoDiscovered: false,
        createdAt: daysAgo(35),
        updatedAt: daysAgo(10),
    },
    {
        id: 'lead-013',
        name: 'Raj Malhotra',
        company: 'Pinnacle Security Group',
        email: 'raj.m@pinnaclesec.com',
        phone: '+1 (571) 555-0409',
        source: LeadSource.COLD,
        status: LeadStatus.NEW,
        value: 35000,
        notes: 'Enterprise security audit portal. SOC 2 compliance reporting. Needs NDA before scoping.',
        isAutoDiscovered: true,
        searchKeywords: ['cybersecurity', 'compliance', 'SOC 2', 'audit'],
        createdAt: daysAgo(3),
        updatedAt: daysAgo(3),
    },
    {
        id: 'lead-014',
        name: 'Sophie Dubois',
        company: 'Altair Robotics',
        email: 'sdubois@altairrobotics.ai',
        source: LeadSource.INDEED,
        status: LeadStatus.NEGOTIATION,
        value: 45000,
        notes: 'ML model deployment pipeline UI. Complex project with multi-phase rollout. High value.',
        nextFollowUp: daysAgo(-2).toISOString(),
        isAutoDiscovered: true,
        searchKeywords: ['ML', 'AI', 'pipeline', 'deployment'],
        createdAt: daysAgo(25),
        updatedAt: daysAgo(1),
    },
    {
        id: 'lead-015',
        name: 'Nathan Brooks',
        company: 'Trailhead Outdoors',
        email: 'nathan@trailheadoutdoors.com',
        phone: '+1 (303) 555-0178',
        source: LeadSource.REFERRAL,
        status: LeadStatus.LOST,
        value: 5600,
        notes: 'E-commerce redesign. Budget too tight for scope. Recommended a junior freelancer.',
        isAutoDiscovered: false,
        createdAt: daysAgo(40),
        updatedAt: daysAgo(20),
        isFlagged: true,
        flags: [
            {
                id: 'flag-001',
                leadId: 'lead-015',
                reasons: ['company_too_small' as any],
                notes: 'Budget does not align with project scope',
                createdAt: daysAgo(20),
            },
        ],
    },
];

export const DUMMY_STATS: LeadStats = {
    total: 15,
    autoDiscovered: 9,
    manual: 6,
    totalValue: 224050,
    followUpsDue: 4,
    byStatus: {
        new: 3,
        contacted: 2,
        qualified: 2,
        proposal: 2,
        negotiation: 2,
        won: 2,
        lost: 2,
    },
    qualification: {
        byClassification: {
            'strong-match': 6,
            review: 7,
            'weak-match': 2,
        },
        averageRelevanceScore: 76,
        averageDifficultyScore: 59,
        averageUserFitScore: 81,
        missingUserFitCount: 1,
    },
};

export const DUMMY_TOPICS: Topic[] = [
    {
        id: 'topic-001',
        name: 'React Development Contracts',
        description:
            'Find clients seeking React, Next.js, or React Native development work.',
        enabled: true,
        keywords: [
            'react',
            'next.js',
            'react native',
            'frontend',
            'component library',
        ],
        excludedTerms: ['wordpress', 'php'],
        discoveryIntent: LeadTopicDiscoveryIntent.JOB_OPENINGS,
        sources: [LeadDiscoverySource.REMOTE_OK, LeadDiscoverySource.WE_WORK_REMOTELY],
        lastRun: daysAgo(1),
        leadCount: 4,
    },
    {
        id: 'topic-002',
        name: 'Cloud Migration Projects',
        description:
            'Organizations moving from on-premise to AWS, Azure, or GCP infrastructure.',
        enabled: true,
        keywords: [
            'cloud migration',
            'AWS',
            'Azure',
            'GCP',
            'infrastructure',
            'DevOps',
        ],
        excludedTerms: [],
        discoveryIntent: LeadTopicDiscoveryIntent.JOB_OPENINGS,
        sources: [LeadDiscoverySource.CRUNCHBASE, LeadDiscoverySource.INDEED],
        lastRun: daysAgo(1),
        leadCount: 2,
    },
    {
        id: 'topic-003',
        name: 'DevOps & CI/CD Consulting',
        description:
            'Teams looking for pipeline automation, containerization, and deployment expertise.',
        enabled: true,
        keywords: [
            'DevOps',
            'CI/CD',
            'Docker',
            'Kubernetes',
            'pipeline',
            'GitHub Actions',
        ],
        excludedTerms: ['wordpress'],
        discoveryIntent: LeadTopicDiscoveryIntent.JOB_OPENINGS,
        sources: [LeadDiscoverySource.JUST_REMOTE, LeadDiscoverySource.JOBICY],
        lastRun: daysAgo(2),
        leadCount: 1,
    },
    {
        id: 'topic-004',
        name: 'Enterprise SaaS Integrations',
        description:
            'Companies needing API integrations between enterprise tools like Salesforce, HubSpot, or SAP.',
        enabled: false,
        keywords: [
            'API integration',
            'Salesforce',
            'HubSpot',
            'SAP',
            'enterprise',
            'middleware',
        ],
        excludedTerms: [],
        discoveryIntent: LeadTopicDiscoveryIntent.SERVICE_BUYERS,
        sources: [LeadDiscoverySource.CLUTCH, LeadDiscoverySource.CRUNCHBASE],
        leadCount: 0,
    },
    {
        id: 'topic-005',
        name: 'Mobile App Development',
        description:
            'Cross-platform or native mobile app projects for iOS and Android.',
        enabled: true,
        keywords: [
            'mobile app',
            'iOS',
            'Android',
            'React Native',
            'Flutter',
            'cross-platform',
        ],
        excludedTerms: ['wordpress', 'wix'],
        discoveryIntent: LeadTopicDiscoveryIntent.JOB_OPENINGS,
        sources: [LeadDiscoverySource.REMOTE_OK, LeadDiscoverySource.HIMALAYAS],
        lastRun: daysAgo(1),
        leadCount: 3,
    },
    {
        id: 'topic-006',
        name: 'Cybersecurity Assessments',
        description:
            'Organizations seeking security audits, penetration testing, or compliance consulting.',
        enabled: false,
        keywords: [
            'cybersecurity',
            'pentest',
            'SOC 2',
            'compliance',
            'security audit',
            'vulnerability',
        ],
        excludedTerms: [],
        discoveryIntent: LeadTopicDiscoveryIntent.SERVICE_BUYERS,
        sources: [LeadDiscoverySource.INDEED, LeadDiscoverySource.CLUTCH],
        leadCount: 1,
    },
    {
        id: 'topic-007',
        name: 'Data Engineering Pipelines',
        description:
            'Building ETL pipelines, data warehouses, and analytics infrastructure.',
        enabled: true,
        keywords: [
            'data engineering',
            'ETL',
            'data warehouse',
            'Snowflake',
            'dbt',
            'Airflow',
        ],
        excludedTerms: ['php'],
        discoveryIntent: LeadTopicDiscoveryIntent.JOB_OPENINGS,
        sources: [LeadDiscoverySource.HIMALAYAS, LeadDiscoverySource.JOBICY],
        lastRun: daysAgo(3),
        leadCount: 2,
    },
    {
        id: 'topic-008',
        name: 'AI / ML Implementation',
        description:
            'Teams needing ML model deployment, training pipelines, or AI-powered feature development.',
        enabled: true,
        keywords: [
            'machine learning',
            'AI',
            'ML pipeline',
            'model deployment',
            'LLM',
            'NLP',
        ],
        excludedTerms: ['wordpress', 'php'],
        discoveryIntent: LeadTopicDiscoveryIntent.SERVICE_BUYERS,
        sources: [LeadDiscoverySource.GOOGLE_MAPS, LeadDiscoverySource.CRUNCHBASE],
        googleMapsCities: ['Austin, TX', 'Raleigh, NC'],
        googleMapsTypes: ['software company', 'AI consultant'],
        lastRun: daysAgo(1),
        leadCount: 2,
    },
];
