#!/usr/bin/env python3
"""
Seed Data Generator for Local Hub
Generates expanded seed data with cities, towns, and neighborhoods.
"""

import json
import random

random.seed(42)

CITIES = [
    # Georgia
    {
        "name": "Atlanta, GA",
        "slug": "atlanta-ga",
        "city": "Atlanta",
        "state": "GA",
        "lat": 33.749,
        "lng": -84.388,
        "population": 496441,
        "localityType": "city",
    },
    {
        "name": "Savannah, GA",
        "slug": "savannah-ga",
        "city": "Savannah",
        "state": "GA",
        "lat": 32.0809,
        "lng": -81.0912,
        "population": 147088,
        "localityType": "city",
    },
    {
        "name": "Augusta, GA",
        "slug": "augusta-ga",
        "city": "Augusta",
        "state": "GA",
        "lat": 33.4404,
        "lng": -81.9618,
        "population": 197166,
        "localityType": "city",
    },
    {
        "name": "Columbus, GA",
        "slug": "columbus-ga",
        "city": "Columbus",
        "state": "GA",
        "lat": 32.5102,
        "lng": -84.8772,
        "population": 206922,
        "localityType": "city",
    },
    {
        "name": "Macon, GA",
        "slug": "macon-ga",
        "city": "Macon",
        "state": "GA",
        "lat": 32.8407,
        "lng": -83.6324,
        "population": 153095,
        "localityType": "city",
    },
    {
        "name": "Athens, GA",
        "slug": "athens-ga",
        "city": "Athens",
        "state": "GA",
        "lat": 33.9519,
        "lng": -83.3576,
        "population": 127315,
        "localityType": "city",
    },
    {
        "name": "Albany, GA",
        "slug": "albany-ga",
        "city": "Albany",
        "state": "GA",
        "lat": 31.5785,
        "lng": -84.1557,
        "population": 68819,
        "localityType": "city",
    },
    {
        "name": "Albany, GA",
        "slug": "albany-ga",
        "city": "Albany",
        "state": "GA",
        "lat": 31.5785,
        "lng": -84.1557,
        "population": 68819,
        "localityType": "city",
    },
    {
        "name": "Rome, GA",
        "slug": "rome-ga",
        "city": "Rome",
        "state": "GA",
        "lat": 34.257,
        "lng": -85.1647,
        "population": 98080,
        "localityType": "city",
    },
    {
        "name": "Gainesville, GA",
        "slug": "gainesville-ga",
        "city": "Gainesville",
        "state": "GA",
        "lat": 34.2979,
        "lng": -83.9879,
        "population": 42000,
        "localityType": "city",
    },
    {
        "name": "Valdosta, GA",
        "slug": "valdosta-ga",
        "city": "Valdosta",
        "state": "GA",
        "lat": 30.8327,
        "lng": -83.2785,
        "population": 57597,
        "localityType": "city",
    },
    {
        "name": "Warner Robins, GA",
        "slug": "warner-robins-ga",
        "city": "Warner Robins",
        "state": "GA",
        "lat": 32.6099,
        "lng": -83.6013,
        "population": 83793,
        "localityType": "city",
    },
    {
        "name": "Dalton, GA",
        "slug": "dalton-ga",
        "city": "Dalton",
        "state": "GA",
        "lat": 34.7698,
        "lng": -84.9702,
        "population": 56000,
        "localityType": "city",
    },
    {
        "name": "LaGrange, GA",
        "slug": "lagrange-ga",
        "city": "LaGrange",
        "state": "GA",
        "lat": 33.034,
        "lng": -85.0316,
        "population": 31000,
        "localityType": "city",
    },
    {
        "name": "Thomasville, GA",
        "slug": "thomasville-ga",
        "city": "Thomasville",
        "state": "GA",
        "lat": 30.8366,
        "lng": -83.9783,
        "population": 19000,
        "localityType": "city",
    },
    {
        "name": "Tifton, GA",
        "slug": "tifton-ga",
        "city": "Tifton",
        "state": "GA",
        "lat": 31.4595,
        "lng": -83.5085,
        "population": 17000,
        "localityType": "city",
    },
    {
        "name": "Dublin, GA",
        "slug": "dublin-ga",
        "city": "Dublin",
        "state": "GA",
        "lat": 32.5405,
        "lng": -82.9035,
        "population": 16000,
        "localityType": "city",
    },
    # South Carolina
    {
        "name": "Charleston, SC",
        "slug": "charleston-sc",
        "city": "Charleston",
        "state": "SC",
        "lat": 32.7765,
        "lng": -79.9311,
        "population": 155369,
        "localityType": "city",
    },
    {
        "name": "Columbia, SC",
        "slug": "columbia-sc",
        "city": "Columbia",
        "state": "SC",
        "lat": 34.0007,
        "lng": -81.0348,
        "population": 127395,
        "localityType": "city",
    },
    {
        "name": "Greenville, SC",
        "slug": "greenville-sc",
        "city": "Greenville",
        "state": "SC",
        "lat": 34.8526,
        "lng": -82.394,
        "population": 72540,
        "localityType": "city",
    },
    {
        "name": "Myrtle Beach, SC",
        "slug": "myrtle-beach-sc",
        "city": "Myrtle Beach",
        "state": "SC",
        "lat": 33.6891,
        "lng": -78.8867,
        "population": 35682,
        "localityType": "city",
    },
    {
        "name": "Spartanburg, SC",
        "slug": "spartanburg-sc",
        "city": "Spartanburg",
        "state": "SC",
        "lat": 34.9496,
        "lng": -81.9321,
        "population": 38217,
        "localityType": "city",
    },
    {
        "name": "Rock Hill, SC",
        "slug": "rock-hill-sc",
        "city": "Rock Hill",
        "state": "SC",
        "lat": 34.9249,
        "lng": -81.0251,
        "population": 75048,
        "localityType": "city",
    },
    {
        "name": "Florence, SC",
        "slug": "florence-sc",
        "city": "Florence",
        "state": "SC",
        "lat": 34.1954,
        "lng": -79.7626,
        "population": 37756,
        "localityType": "city",
    },
    {
        "name": "Beaufort, SC",
        "slug": "beaufort-sc",
        "city": "Beaufort",
        "state": "SC",
        "lat": 32.4316,
        "lng": -80.6698,
        "population": 31317,
        "localityType": "city",
    },
    {
        "name": "Hilton Head Island, SC",
        "slug": "hilton-head-island-sc",
        "city": "Hilton Head Island",
        "state": "SC",
        "lat": 32.2163,
        "lng": -80.7526,
        "population": 39661,
        "localityType": "city",
    },
    {
        "name": "Anderson, SC",
        "slug": "anderson-sc",
        "city": "Anderson",
        "state": "SC",
        "lat": 34.5033,
        "lng": -82.6501,
        "population": 27737,
        "localityType": "city",
    },
    {
        "name": "Greer, SC",
        "slug": "greer-sc",
        "city": "Greer",
        "state": "SC",
        "lat": 34.9387,
        "lng": -82.227,
        "population": 33500,
        "localityType": "city",
    },
    {
        "name": "Conway, SC",
        "slug": "conway-sc",
        "city": "Conway",
        "state": "SC",
        "lat": 33.836,
        "lng": -79.0472,
        "population": 24000,
        "localityType": "city",
    },
    {
        "name": "Sumter, SC",
        "slug": "sumter-sc",
        "city": "Sumter",
        "state": "SC",
        "lat": 33.9207,
        "lng": -80.3417,
        "population": 40500,
        "localityType": "city",
    },
    {
        "name": "Gaffney, SC",
        "slug": "gaffney-sc",
        "city": "Gaffney",
        "state": "SC",
        "lat": 35.0718,
        "lng": -81.6498,
        "population": 12500,
        "localityType": "city",
    },
    {
        "name": "Lancaster, SC",
        "slug": "lancaster-sc",
        "city": "Lancaster",
        "state": "SC",
        "lat": 34.7204,
        "lng": -80.7742,
        "population": 8900,
        "localityType": "city",
    },
    {
        "name": "Georgetown, SC",
        "slug": "georgetown-sc",
        "city": "Georgetown",
        "state": "SC",
        "lat": 33.3771,
        "lng": -79.2945,
        "population": 9400,
        "localityType": "city",
    },
    {
        "name": "Greenwood, SC",
        "slug": "greenwood-sc",
        "city": "Greenwood",
        "state": "SC",
        "lat": 34.1954,
        "lng": -82.1629,
        "population": 23000,
        "localityType": "city",
    },
    # Florida
    {
        "name": "Jacksonville, FL",
        "slug": "jacksonville-fl",
        "city": "Jacksonville",
        "state": "FL",
        "lat": 30.3322,
        "lng": -81.6557,
        "population": 911507,
        "localityType": "city",
    },
    {
        "name": "Miami, FL",
        "slug": "miami-fl",
        "city": "Miami",
        "state": "FL",
        "lat": 25.7617,
        "lng": -80.1918,
        "population": 449514,
        "localityType": "city",
    },
    {
        "name": "Tampa, FL",
        "slug": "tampa-fl",
        "city": "Tampa",
        "state": "FL",
        "lat": 27.9506,
        "lng": -82.4572,
        "population": 395912,
        "localityType": "city",
    },
    {
        "name": "Orlando, FL",
        "slug": "orlando-fl",
        "city": "Orlando",
        "state": "FL",
        "lat": 28.5383,
        "lng": -81.3792,
        "population": 289457,
        "localityType": "city",
    },
    {
        "name": "St. Petersburg, FL",
        "slug": "st-petersburg-fl",
        "city": "St. Petersburg",
        "state": "FL",
        "lat": 27.7676,
        "lng": -82.6403,
        "population": 265098,
        "localityType": "city",
    },
    {
        "name": "Fort Lauderdale, FL",
        "slug": "fort-lauderdale-fl",
        "city": "Fort Lauderdale",
        "state": "FL",
        "lat": 26.1224,
        "lng": -80.1373,
        "population": 183606,
        "localityType": "city",
    },
    {
        "name": "Tallahassee, FL",
        "slug": "tallahassee-fl",
        "city": "Tallahassee",
        "state": "FL",
        "lat": 30.4383,
        "lng": -84.2807,
        "population": 196165,
        "localityType": "city",
    },
    {
        "name": "Gainesville, FL",
        "slug": "gainesville-fl",
        "city": "Gainesville",
        "state": "FL",
        "lat": 29.6516,
        "lng": -82.3248,
        "population": 133997,
        "localityType": "city",
    },
    {
        "name": "Fort Myers, FL",
        "slug": "fort-myers-fl",
        "city": "Fort Myers",
        "state": "FL",
        "lat": 26.6406,
        "lng": -81.8723,
        "population": 92310,
        "localityType": "city",
    },
    {
        "name": "Sarasota, FL",
        "slug": "sarasota-fl",
        "city": "Sarasota",
        "state": "FL",
        "lat": 27.3364,
        "lng": -82.5307,
        "population": 57590,
        "localityType": "city",
    },
    {
        "name": "West Palm Beach, FL",
        "slug": "west-palm-beach-fl",
        "city": "West Palm Beach",
        "state": "FL",
        "lat": 26.7153,
        "lng": -80.0534,
        "population": 117415,
        "localityType": "city",
    },
    {
        "name": "Daytona Beach, FL",
        "slug": "daytona-beach-fl",
        "city": "Daytona Beach",
        "state": "FL",
        "lat": 29.2108,
        "lng": -81.0228,
        "population": 73782,
        "localityType": "city",
    },
    {
        "name": "Pensacola, FL",
        "slug": "pensacola-fl",
        "city": "Pensacola",
        "state": "FL",
        "lat": 30.4213,
        "lng": -87.2169,
        "population": 52821,
        "localityType": "city",
    },
    {
        "name": "St. Augustine, FL",
        "slug": "st-augustine-fl",
        "city": "St. Augustine",
        "state": "FL",
        "lat": 29.8944,
        "lng": -81.315,
        "population": 14479,
        "localityType": "city",
    },
    {
        "name": "Naples, FL",
        "slug": "naples-fl",
        "city": "Naples",
        "state": "FL",
        "lat": 26.142,
        "lng": -81.7948,
        "population": 22307,
        "localityType": "city",
    },
    {
        "name": "Kissimmee, FL",
        "slug": "kissimmee-fl",
        "city": "Kissimmee",
        "state": "FL",
        "lat": 28.3045,
        "lng": -81.4176,
        "population": 71735,
        "localityType": "city",
    },
    {
        "name": "Clearwater, FL",
        "slug": "clearwater-fl",
        "city": "Clearwater",
        "state": "FL",
        "lat": 27.9659,
        "lng": -82.8001,
        "population": 117292,
        "localityType": "city",
    },
    {
        "name": "Lakeland, FL",
        "slug": "lakeland-fl",
        "city": "Lakeland",
        "state": "FL",
        "lat": 28.0395,
        "lng": -81.9498,
        "population": 115650,
        "localityType": "city",
    },
    {
        "name": "Ocala, FL",
        "slug": "ocala-fl",
        "city": "Ocala",
        "state": "FL",
        "lat": 29.1872,
        "lng": -82.1401,
        "population": 60170,
        "localityType": "city",
    },
    {
        "name": "Melbourne, FL",
        "slug": "melbourne-fl",
        "city": "Melbourne",
        "state": "FL",
        "lat": 28.1916,
        "lng": -80.6706,
        "population": 83829,
        "localityType": "city",
    },
    {
        "name": "Boca Raton, FL",
        "slug": "boca-raton-fl",
        "city": "Boca Raton",
        "state": "FL",
        "lat": 26.3683,
        "lng": -80.1289,
        "population": 99737,
        "localityType": "city",
    },
    {
        "name": "Palm Bay, FL",
        "slug": "palm-bay-fl",
        "city": "Palm Bay",
        "state": "FL",
        "lat": 28.0345,
        "lng": -80.5887,
        "population": 119760,
        "localityType": "city",
    },
    {
        "name": "DeLand, FL",
        "slug": "deland-fl",
        "city": "DeLand",
        "state": "FL",
        "lat": 29.0283,
        "lng": -81.3031,
        "population": 35000,
        "localityType": "city",
    },
    {
        "name": "Fernandina Beach, FL",
        "slug": "fernandina-beach-fl",
        "city": "Fernandina Beach",
        "state": "FL",
        "lat": 30.6719,
        "lng": -81.4623,
        "population": 13490,
        "localityType": "city",
    },
    {
        "name": "Destin, FL",
        "slug": "destin-fl",
        "city": "Destin",
        "state": "FL",
        "lat": 30.3935,
        "lng": -86.4958,
        "population": 14520,
        "localityType": "city",
    },
    {
        "name": "Bradenton, FL",
        "slug": "bradenton-fl",
        "city": "Bradenton",
        "state": "FL",
        "lat": 27.4989,
        "lng": -82.5748,
        "population": 55178,
        "localityType": "city",
    },
    {
        "name": "Cape Coral, FL",
        "slug": "cape-coral-fl",
        "city": "Cape Coral",
        "state": "FL",
        "lat": 26.5629,
        "lng": -81.9495,
        "population": 194535,
        "localityType": "city",
    },
    # North Carolina
    {
        "name": "Charlotte, NC",
        "slug": "charlotte-nc",
        "city": "Charlotte",
        "state": "NC",
        "lat": 35.2271,
        "lng": -80.8431,
        "population": 885708,
        "localityType": "city",
    },
    {
        "name": "Raleigh, NC",
        "slug": "raleigh-nc",
        "city": "Raleigh",
        "state": "NC",
        "lat": 35.7796,
        "lng": -78.6382,
        "population": 458880,
        "localityType": "city",
    },
    {
        "name": "Greensboro, NC",
        "slug": "greensboro-nc",
        "city": "Greensboro",
        "state": "NC",
        "lat": 36.0726,
        "lng": -79.792,
        "population": 296710,
        "localityType": "city",
    },
    {
        "name": "Durham, NC",
        "slug": "durham-nc",
        "city": "Durham",
        "state": "NC",
        "lat": 35.994,
        "lng": -78.8986,
        "population": 295172,
        "localityType": "city",
    },
    {
        "name": "Wilmington, NC",
        "slug": "wilmington-nc",
        "city": "Wilmington",
        "state": "NC",
        "lat": 34.2257,
        "lng": -77.9447,
        "population": 123744,
        "localityType": "city",
    },
    {
        "name": "Winston-Salem, NC",
        "slug": "winston-salem-nc",
        "city": "Winston-Salem",
        "state": "NC",
        "lat": 36.0999,
        "lng": -80.2442,
        "population": 248189,
        "localityType": "city",
    },
    {
        "name": "Fayetteville, NC",
        "slug": "fayetteville-nc",
        "city": "Fayetteville",
        "state": "NC",
        "lat": 35.0527,
        "lng": -78.8784,
        "population": 211657,
        "localityType": "city",
    },
    {
        "name": "Asheville, NC",
        "slug": "asheville-nc",
        "city": "Asheville",
        "state": "NC",
        "lat": 35.5951,
        "lng": -82.5515,
        "population": 91450,
        "localityType": "city",
    },
    {
        "name": "High Point, NC",
        "slug": "high-point-nc",
        "city": "High Point",
        "state": "NC",
        "lat": 35.9557,
        "lng": -80.0053,
        "population": 113565,
        "localityType": "city",
    },
    {
        "name": "Greenville, NC",
        "slug": "greenville-nc",
        "city": "Greenville",
        "state": "NC",
        "lat": 35.6127,
        "lng": -77.366,
        "population": 93605,
        "localityType": "city",
    },
    {
        "name": "Chapel Hill, NC",
        "slug": "chapel-hill-nc",
        "city": "Chapel Hill",
        "state": "NC",
        "lat": 35.9132,
        "lng": -79.0558,
        "population": 60885,
        "localityType": "city",
    },
    {
        "name": "Cary, NC",
        "slug": "cary-nc",
        "city": "Cary",
        "state": "NC",
        "lat": 35.7915,
        "lng": -78.7811,
        "population": 170282,
        "localityType": "city",
    },
    {
        "name": "Boone, NC",
        "slug": "boone-nc",
        "city": "Boone",
        "state": "NC",
        "lat": 36.216,
        "lng": -81.6745,
        "population": 20212,
        "localityType": "city",
    },
    {
        "name": "Hickory, NC",
        "slug": "hickory-nc",
        "city": "Hickory",
        "state": "NC",
        "lat": 35.7345,
        "lng": -81.3445,
        "population": 55535,
        "localityType": "city",
    },
    {
        "name": "New Bern, NC",
        "slug": "new-bern-nc",
        "city": "New Bern",
        "state": "NC",
        "lat": 35.1082,
        "lng": -77.0441,
        "population": 31666,
        "localityType": "city",
    },
    {
        "name": "Outer Banks, NC",
        "slug": "outer-banks-nc",
        "city": "Kill Devil Hills",
        "state": "NC",
        "lat": 36.0306,
        "lng": -75.6767,
        "population": 7420,
        "localityType": "city",
    },
]

TOWNS = [
    # Georgia Towns
    {
        "name": "Tybee Island, GA",
        "slug": "tybee-island-ga",
        "city": "Tybee Island",
        "state": "GA",
        "lat": 32.0,
        "lng": -80.85,
        "population": 3500,
        "localityType": "town",
    },
    {
        "name": "St. Simons Island, GA",
        "slug": "st-simons-island-ga",
        "city": "St. Simons Island",
        "state": "GA",
        "lat": 31.1535,
        "lng": -81.3966,
        "population": 13381,
        "localityType": "town",
    },
    {
        "name": "Jekyll Island, GA",
        "slug": "jekyll-island-ga",
        "city": "Jekyll Island",
        "state": "GA",
        "lat": 31.0567,
        "lng": -81.4293,
        "population": 1200,
        "localityType": "town",
    },
    {
        "name": "Sea Island, GA",
        "slug": "sea-island-ga",
        "city": "Sea Island",
        "state": "GA",
        "lat": 31.225,
        "lng": -81.365,
        "population": 600,
        "localityType": "town",
    },
    {
        "name": "Dahlonega, GA",
        "slug": "dahlonega-ga",
        "city": "Dahlonega",
        "state": "GA",
        "lat": 34.5341,
        "lng": -83.9852,
        "population": 7800,
        "localityType": "town",
    },
    {
        "name": "Ellijay, GA",
        "slug": "ellijay-ga",
        "city": "Ellijay",
        "state": "GA",
        "lat": 34.6968,
        "lng": -84.4869,
        "population": 1800,
        "localityType": "town",
    },
    {
        "name": "Helen, GA",
        "slug": "helen-ga",
        "city": "Helen",
        "state": "GA",
        "lat": 34.7029,
        "lng": -83.7297,
        "population": 650,
        "localityType": "town",
    },
    {
        "name": "Madison, GA",
        "slug": "madison-ga",
        "city": "Madison",
        "state": "GA",
        "lat": 33.5957,
        "lng": -83.4698,
        "population": 4500,
        "localityType": "town",
    },
    {
        "name": "Milledgeville, GA",
        "slug": "milledgeville-ga",
        "city": "Milledgeville",
        "state": "GA",
        "lat": 33.0802,
        "lng": -83.2321,
        "population": 18500,
        "localityType": "town",
    },
    {
        "name": "Woodstock, GA",
        "slug": "woodstock-ga",
        "city": "Woodstock",
        "state": "GA",
        "lat": 34.1014,
        "lng": -84.5194,
        "population": 33000,
        "localityType": "town",
    },
    {
        "name": "Woodbine, GA",
        "slug": "woodbine-ga",
        "city": "Woodbine",
        "state": "GA",
        "lat": 30.9638,
        "lng": -81.7226,
        "population": 1400,
        "localityType": "town",
    },
    # South Carolina Towns
    {
        "name": "Bluffton, SC",
        "slug": "bluffton-sc",
        "city": "Bluffton",
        "state": "SC",
        "lat": 32.2371,
        "lng": -80.8601,
        "population": 28204,
        "localityType": "town",
    },
    {
        "name": "Edisto Island, SC",
        "slug": "edisto-island-sc",
        "city": "Edisto Island",
        "state": "SC",
        "lat": 32.5616,
        "lng": -80.2832,
        "population": 550,
        "localityType": "town",
    },
    {
        "name": "Kiawah Island, SC",
        "slug": "kiawah-island-sc",
        "city": "Kiawah Island",
        "state": "SC",
        "lat": 32.6118,
        "lng": -80.0432,
        "population": 1800,
        "localityType": "town",
    },
    {
        "name": "Isle of Palms, SC",
        "slug": "isle-of-palms-sc",
        "city": "Isle of Palms",
        "state": "SC",
        "lat": 32.7974,
        "lng": -79.7562,
        "population": 4200,
        "localityType": "town",
    },
    {
        "name": "Sullivan's Island, SC",
        "slug": "sullivans-island-sc",
        "city": "Sullivan's Island",
        "state": "SC",
        "lat": 32.7646,
        "lng": -79.8498,
        "population": 2000,
        "localityType": "town",
    },
    {
        "name": "Fripp Island, SC",
        "slug": "fripp-island-sc",
        "city": "Fripp Island",
        "state": "SC",
        "lat": 32.3468,
        "lng": -80.5632,
        "population": 650,
        "localityType": "town",
    },
    {
        "name": "Cheraw, SC",
        "slug": "cheraw-sc",
        "city": "Cheraw",
        "state": "SC",
        "lat": 34.6982,
        "lng": -79.9123,
        "population": 5700,
        "localityType": "town",
    },
    {
        "name": "Camden, SC",
        "slug": "camden-sc",
        "city": "Camden",
        "state": "SC",
        "lat": 34.246,
        "lng": -80.6082,
        "population": 7800,
        "localityType": "town",
    },
    {
        "name": "McCormick, SC",
        "slug": "mccormick-sc",
        "city": "McCormick",
        "state": "SC",
        "lat": 33.978,
        "lng": -82.294,
        "population": 2500,
        "localityType": "town",
    },
    {
        "name": "Edgefield, SC",
        "slug": "edgefield-sc",
        "city": "Edgefield",
        "state": "SC",
        "lat": 33.7795,
        "lng": -81.9296,
        "population": 4300,
        "localityType": "town",
    },
    {
        "name": "Chester, SC",
        "slug": "chester-sc",
        "city": "Chester",
        "state": "SC",
        "lat": 34.7057,
        "lng": -81.2145,
        "population": 5500,
        "localityType": "town",
    },
    # Florida Towns
    {
        "name": "Key West, FL",
        "slug": "key-west-fl",
        "city": "Key West",
        "state": "FL",
        "lat": 24.5551,
        "lng": -81.7801,
        "population": 25000,
        "localityType": "town",
    },
    {
        "name": "Cedar Key, FL",
        "slug": "cedar-key-fl",
        "city": "Cedar Key",
        "state": "FL",
        "lat": 29.1464,
        "lng": -82.8023,
        "population": 700,
        "localityType": "town",
    },
    {
        "name": "Apalachicola, FL",
        "slug": "apalachicola-fl",
        "city": "Apalachicola",
        "state": "FL",
        "lat": 29.7249,
        "lng": -84.9829,
        "population": 2300,
        "localityType": "town",
    },
    {
        "name": "Crystal River, FL",
        "slug": "crystal-river-fl",
        "city": "Crystal River",
        "state": "FL",
        "lat": 28.9022,
        "lng": -82.5887,
        "population": 7500,
        "localityType": "town",
    },
    {
        "name": "Mount Dora, FL",
        "slug": "mount-dora-fl",
        "city": "Mount Dora",
        "state": "FL",
        "lat": 28.8028,
        "lng": -81.6443,
        "population": 15000,
        "localityType": "town",
    },
    {
        "name": "Eustis, FL",
        "slug": "eustis-fl",
        "city": "Eustis",
        "state": "FL",
        "lat": 28.8528,
        "lng": -81.6853,
        "population": 22000,
        "localityType": "town",
    },
    {
        "name": "Sanford, FL",
        "slug": "sanford-fl",
        "city": "Sanford",
        "state": "FL",
        "lat": 28.8028,
        "lng": -81.2692,
        "population": 59000,
        "localityType": "town",
    },
    {
        "name": "Winter Garden, FL",
        "slug": "winter-garden-fl",
        "city": "Winter Garden",
        "state": "FL",
        "lat": 28.5652,
        "lng": -81.5862,
        "population": 47000,
        "localityType": "town",
    },
    {
        "name": "Winter Park, FL",
        "slug": "winter-park-fl",
        "city": "Winter Park",
        "state": "FL",
        "lat": 28.5928,
        "lng": -81.3512,
        "population": 31000,
        "localityType": "town",
    },
    {
        "name": "Micanopy, FL",
        "slug": "micanopy-fl",
        "city": "Micanopy",
        "state": "FL",
        "lat": 29.505,
        "lng": -82.2817,
        "population": 650,
        "localityType": "town",
    },
    {
        "name": "Monticello, FL",
        "slug": "monticello-fl",
        "city": "Monticello",
        "state": "FL",
        "lat": 30.5452,
        "lng": -83.8702,
        "population": 2500,
        "localityType": "town",
    },
    {
        "name": "St. George Island, FL",
        "slug": "st-george-island-fl",
        "city": "St. George Island",
        "state": "FL",
        "lat": 29.6575,
        "lng": -84.9695,
        "population": 550,
        "localityType": "town",
    },
    {
        "name": "Marineland, FL",
        "slug": "marineland-fl",
        "city": "Marineland",
        "state": "FL",
        "lat": 29.6629,
        "lng": -81.2136,
        "population": 15,
        "localityType": "town",
    },
    {
        "name": "Flagler Beach, FL",
        "slug": "flagler-beach-fl",
        "city": "Flagler Beach",
        "state": "FL",
        "lat": 29.475,
        "lng": -81.1267,
        "population": 5200,
        "localityType": "town",
    },
    {
        "name": "Jacksonville Beach, FL",
        "slug": "jacksonville-beach-fl",
        "city": "Jacksonville Beach",
        "state": "FL",
        "lat": 30.2849,
        "lng": -81.393,
        "population": 23600,
        "localityType": "town",
    },
    {
        "name": "Atlantic Beach, FL",
        "slug": "atlantic-beach-fl",
        "city": "Atlantic Beach",
        "state": "FL",
        "lat": 30.3325,
        "lng": -81.4159,
        "population": 13500,
        "localityType": "town",
    },
    {
        "name": "Neptune Beach, FL",
        "slug": "neptune-beach-fl",
        "city": "Neptune Beach",
        "state": "FL",
        "lat": 30.3147,
        "lng": -81.3906,
        "population": 7200,
        "localityType": "town",
    },
    {
        "name": "Ponte Vedra Beach, FL",
        "slug": "ponte-vedra-beach-fl",
        "city": "Ponte Vedra Beach",
        "state": "FL",
        "lat": 30.2408,
        "lng": -81.3895,
        "population": 26000,
        "localityType": "town",
    },
    {
        "name": "Amelia Island, FL",
        "slug": "amelia-island-fl",
        "city": "Amelia Island",
        "state": "FL",
        "lat": 30.6166,
        "lng": -81.4498,
        "population": 1000,
        "localityType": "town",
    },
    # North Carolina Towns
    {
        "name": "Kitty Hawk, NC",
        "slug": "kitty-hawk-nc",
        "city": "Kitty Hawk",
        "state": "NC",
        "lat": 36.0646,
        "lng": -75.708,
        "population": 3600,
        "localityType": "town",
    },
    {
        "name": "Kill Devil Hills, NC",
        "slug": "kill-devil-hills-nc",
        "city": "Kill Devil Hills",
        "state": "NC",
        "lat": 36.0306,
        "lng": -75.6767,
        "population": 7420,
        "localityType": "town",
    },
    {
        "name": "Nags Head, NC",
        "slug": "nags-head-nc",
        "city": "Nags Head",
        "state": "NC",
        "lat": 35.9918,
        "lng": -75.5949,
        "population": 3000,
        "localityType": "town",
    },
    {
        "name": "Duck, NC",
        "slug": "duck-nc",
        "city": "Duck",
        "state": "NC",
        "lat": 36.1666,
        "lng": -75.7555,
        "population": 370,
        "localityType": "town",
    },
    {
        "name": "Corolla, NC",
        "slug": "corolla-nc",
        "city": "Corolla",
        "state": "NC",
        "lat": 36.3786,
        "lng": -75.8319,
        "population": 550,
        "localityType": "town",
    },
    {
        "name": "Hatteras, NC",
        "slug": "hatteras-nc",
        "city": "Hatteras",
        "state": "NC",
        "lat": 35.6935,
        "lng": -75.6902,
        "population": 600,
        "localityType": "town",
    },
    {
        "name": "Cape Hatteras, NC",
        "slug": "cape-hatteras-nc",
        "city": "Cape Hatteras",
        "state": "NC",
        "lat": 35.4433,
        "lng": -75.4733,
        "population": 300,
        "localityType": "town",
    },
    {
        "name": "Beaufort, NC",
        "slug": "beaufort-nc",
        "city": "Beaufort",
        "state": "NC",
        "lat": 34.7182,
        "lng": -76.6537,
        "population": 4350,
        "localityType": "town",
    },
    {
        "name": "Oriental, NC",
        "slug": "oriental-nc",
        "city": "Oriental",
        "state": "NC",
        "lat": 35.0274,
        "lng": -76.7016,
        "population": 900,
        "localityType": "town",
    },
    {
        "name": "Southport, NC",
        "slug": "southport-nc",
        "city": "Southport",
        "state": "NC",
        "lat": 33.9292,
        "lng": -78.0422,
        "population": 3600,
        "localityType": "town",
    },
    {
        "name": "Bald Head Island, NC",
        "slug": "bald-head-island-nc",
        "city": "Bald Head Island",
        "state": "NC",
        "lat": 33.8783,
        "lng": -77.9333,
        "population": 160,
        "localityType": "town",
    },
    {
        "name": "Hillsborough, NC",
        "slug": "hillsborough-nc",
        "city": "Hillsborough",
        "state": "NC",
        "lat": 36.0754,
        "lng": -79.0997,
        "population": 7000,
        "localityType": "town",
    },
    {
        "name": "Pittsboro, NC",
        "slug": "pittsboro-nc",
        "city": "Pittsboro",
        "state": "NC",
        "lat": 35.7204,
        "lng": -79.1772,
        "population": 4500,
        "localityType": "town",
    },
    {
        "name": "Wilmington Island, GA",
        "slug": "wilmington-island-ga",
        "city": "Wilmington Island",
        "state": "GA",
        "lat": 32.0016,
        "lng": -81.0023,
        "population": 17000,
        "localityType": "town",
    },
    {
        "name": "Skidaway Island, GA",
        "slug": "skidaway-island-ga",
        "city": "Skidaway Island",
        "state": "GA",
        "lat": 31.9388,
        "lng": -81.0179,
        "population": 8500,
        "localityType": "town",
    },
    {
        "name": "Richmond Hill, GA",
        "slug": "richmond-hill-ga",
        "city": "Richmond Hill",
        "state": "GA",
        "lat": 31.9385,
        "lng": -81.3018,
        "population": 14259,
        "localityType": "town",
    },
    {
        "name": "Pooler, GA",
        "slug": "pooler-ga",
        "city": "Pooler",
        "state": "GA",
        "lat": 32.1119,
        "lng": -81.2448,
        "population": 25000,
        "localityType": "town",
    },
    {
        "name": "Rincon, GA",
        "slug": "rincon-ga",
        "city": "Rincon",
        "state": "GA",
        "lat": 32.2949,
        "lng": -81.2357,
        "population": 11039,
        "localityType": "town",
    },
    {
        "name": "Hinesville, GA",
        "slug": "hinesville-ga",
        "city": "Hinesville",
        "state": "GA",
        "lat": 31.8468,
        "lng": -81.5957,
        "population": 34249,
        "localityType": "town",
    },
    {
        "name": "Statesboro, GA",
        "slug": "statesboro-ga",
        "city": "Statesboro",
        "state": "GA",
        "lat": 32.4488,
        "lng": -81.7832,
        "population": 33521,
        "localityType": "town",
    },
    {
        "name": "Brunswick, GA",
        "slug": "brunswick-ga",
        "city": "Brunswick",
        "state": "GA",
        "lat": 31.15,
        "lng": -81.4915,
        "population": 16257,
        "localityType": "town",
    },
    {
        "name": " Hinesville, GA",
        "slug": "hinesville-ga",
        "city": "Hinesville",
        "state": "GA",
        "lat": 31.8468,
        "lng": -81.5957,
        "population": 34249,
        "localityType": "town",
    },
]

NEIGHBORHOODS = {
    "savannah-ga": [
        {
            "name": "Historic District",
            "slug": "savannah-historic-district",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Starland District",
            "slug": "savannah-starland-district",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Victorian District",
            "slug": "savannah-victorian-district",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Southside Savannah",
            "slug": "savannah-southside",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Ardsley Park",
            "slug": "ardsley-park-savannah",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Wilmington Island",
            "slug": "wilmington-island-savannah",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Skidaway Island",
            "slug": "skidaway-island",
            "city": "Savannah",
            "state": "GA",
        },
        {"name": "Pooler", "slug": "pooler-ga", "city": "Savannah", "state": "GA"},
        {
            "name": "Midtown Savannah",
            "slug": "midtown-savannah",
            "city": "Savannah",
            "state": "GA",
        },
        {
            "name": "Oglethorpe Avenue",
            "slug": "oglethorpe-savannah",
            "city": "Savannah",
            "state": "GA",
        },
    ],
    "charleston-sc": [
        {
            "name": "Downtown Charleston",
            "slug": "downtown-charleston",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "Historic District",
            "slug": "charleston-historic-district",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "Mount Pleasant",
            "slug": "mount-pleasant-charleston",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "James Island",
            "slug": "james-island-charleston",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "Johns Island",
            "slug": "johns-island-charleston",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "West Ashley",
            "slug": "west-ashley-charleston",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "North Charleston",
            "slug": "north-charleston",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "Daniel Island",
            "slug": "daniel-island",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "Folly Beach",
            "slug": "folly-beach",
            "city": "Charleston",
            "state": "SC",
        },
        {
            "name": "Kiawah Island",
            "slug": "kiawah-island-charleston",
            "city": "Charleston",
            "state": "SC",
        },
    ],
    "jacksonville-fl": [
        {
            "name": "Riverside",
            "slug": "riverside-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Avondale",
            "slug": "avondale-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "San Marco",
            "slug": "san-marco-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Springfield",
            "slug": "springfield-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Mandarin",
            "slug": "mandarin-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Ponte Vedra",
            "slug": "ponte-vedra-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Atlantic Beach",
            "slug": "atlantic-beach-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Neptune Beach",
            "slug": "neptune-beach-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Baymeadows",
            "slug": "baymeadows-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
        {
            "name": "Southside",
            "slug": "southside-jacksonville",
            "city": "Jacksonville",
            "state": "FL",
        },
    ],
    "atlanta-ga": [
        {
            "name": "Virginia-Highland",
            "slug": "virginia-highland-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Inman Park",
            "slug": "inman-park-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Old Fourth Ward",
            "slug": "old-fourth-ward-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Buckhead",
            "slug": "buckhead-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Midtown",
            "slug": "midtown-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Decatur",
            "slug": "decatur-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "West Midtown",
            "slug": "west-midtown-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "East Atlanta",
            "slug": "east-atlanta-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Grant Park",
            "slug": "grant-park-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
        {
            "name": "Poncey-Highland",
            "slug": "poncey-highland-atlanta",
            "city": "Atlanta",
            "state": "GA",
        },
    ],
    "charlotte-nc": [
        {
            "name": "Uptown Charlotte",
            "slug": "uptown-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "South End",
            "slug": "south-end-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {"name": "NoDa", "slug": "noda-charlotte", "city": "Charlotte", "state": "NC"},
        {
            "name": "Dilworth",
            "slug": "dilworth-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "Myers Park",
            "slug": "myers-park-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "Eastover",
            "slug": "eastover-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "Cotswold",
            "slug": "cotswold-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "Plaza Midwood",
            "slug": "plaza-midwood-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "SouthPark",
            "slug": "southpark-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
        {
            "name": "University City",
            "slug": "university-city-charlotte",
            "city": "Charlotte",
            "state": "NC",
        },
    ],
    "orlando-fl": [
        {
            "name": "Downtown Orlando",
            "slug": "downtown-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Winter Park",
            "slug": "winter-park-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "College Park",
            "slug": "college-park-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Mills 50",
            "slug": "mills-50-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Ivanhoe Village",
            "slug": "ivanhoe-village-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Thornton Park",
            "slug": "thornton-park-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Audubon Park",
            "slug": "audubon-park-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Lake Eola",
            "slug": "lake-eola-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Kissimmee",
            "slug": "kissimmee-orlando",
            "city": "Orlando",
            "state": "FL",
        },
        {
            "name": "Winter Garden",
            "slug": "winter-garden-orlando",
            "city": "Orlando",
            "state": "FL",
        },
    ],
    "raleigh-nc": [
        {
            "name": "Downtown Raleigh",
            "slug": "downtown-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "North Hills",
            "slug": "north-hills-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Glenwood South",
            "slug": "glenwood-south-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Fayetteville Street",
            "slug": "fayetteville-street-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Cameron Village",
            "slug": "cameron-village-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Boylan Heights",
            "slug": "boylan-heights-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Oakwood",
            "slug": "oakwood-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Moore Square",
            "slug": "moore-square-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {
            "name": "Midtown Raleigh",
            "slug": "midtown-raleigh",
            "city": "Raleigh",
            "state": "NC",
        },
        {"name": "Cary", "slug": "cary-raleigh", "city": "Raleigh", "state": "NC"},
    ],
    "tampa-fl": [
        {
            "name": "Downtown Tampa",
            "slug": "downtown-tampa",
            "city": "Tampa",
            "state": "FL",
        },
        {
            "name": "Hyde Park",
            "slug": "hyde-park-tampa",
            "city": "Tampa",
            "state": "FL",
        },
        {"name": "SoHo", "slug": "soho-tampa", "city": "Tampa", "state": "FL"},
        {
            "name": "Ybor City",
            "slug": "ybor-city-tampa",
            "city": "Tampa",
            "state": "FL",
        },
        {
            "name": "Channel District",
            "slug": "channel-district-tampa",
            "city": "Tampa",
            "state": "FL",
        },
        {
            "name": "Harbour Island",
            "slug": "harbour-island-tampa",
            "city": "Tampa",
            "state": "FL",
        },
        {"name": "West Tampa", "slug": "west-tampa", "city": "Tampa", "state": "FL"},
        {
            "name": "Tampa Heights",
            "slug": "tampa-heights",
            "city": "Tampa",
            "state": "FL",
        },
        {
            "name": "Seminole Heights",
            "slug": "seminole-heights-tampa",
            "city": "Tampa",
            "state": "FL",
        },
        {
            "name": "Davis Islands",
            "slug": "davis-islands-tampa",
            "city": "Tampa",
            "state": "FL",
        },
    ],
    "miami-fl": [
        {"name": "Wynwood", "slug": "wynwood-miami", "city": "Miami", "state": "FL"},
        {"name": "Brickell", "slug": "brickell-miami", "city": "Miami", "state": "FL"},
        {
            "name": "South Beach",
            "slug": "south-beach-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Design District",
            "slug": "design-district-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Coral Gables",
            "slug": "coral-gables-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Coconut Grove",
            "slug": "coconut-grove-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Key Biscayne",
            "slug": "key-biscayne-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Edgewater",
            "slug": "edgewater-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Midtown Miami",
            "slug": "midtown-miami",
            "city": "Miami",
            "state": "FL",
        },
        {
            "name": "Little Havana",
            "slug": "little-havana-miami",
            "city": "Miami",
            "state": "FL",
        },
    ],
    "greenville-sc": [
        {
            "name": "Downtown Greenville",
            "slug": "downtown-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "West End",
            "slug": "west-end-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "Falls Park",
            "slug": "falls-park-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "Main Street",
            "slug": "main-street-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "Augusta Street",
            "slug": "augusta-street-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "Overbrook",
            "slug": "overbrook-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "Gower Estates",
            "slug": "gower-estates-greenville",
            "city": "Greenville",
            "state": "SC",
        },
        {
            "name": "Silverleaf",
            "slug": "silverleaf-greenville",
            "city": "Greenville",
            "state": "SC",
        },
    ],
    "nashville-tn": [
        {
            "name": "Downtown Nashville",
            "slug": "downtown-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "East Nashville",
            "slug": "east-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "Germantown",
            "slug": "germantown-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "The Gulch",
            "slug": "the-gulch-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "12 South",
            "slug": "12-south-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "Music Row",
            "slug": "music-row-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "Hillsboro Village",
            "slug": "hillsboro-village-nashville",
            "city": "Nashville",
            "state": "TN",
        },
        {
            "name": "Green Hills",
            "slug": "green-hills-nashville",
            "city": "Nashville",
            "state": "TN",
        },
    ],
    "asheville-nc": [
        {
            "name": "Downtown Asheville",
            "slug": "downtown-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "Biltmore Village",
            "slug": "biltmore-village-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "West Asheville",
            "slug": "west-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "North Asheville",
            "slug": "north-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "Montford",
            "slug": "montford-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "River Arts District",
            "slug": "river-arts-district-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "South Asheville",
            "slug": "south-asheville",
            "city": "Asheville",
            "state": "NC",
        },
        {
            "name": "Woodfin",
            "slug": "woodfin-asheville",
            "city": "Asheville",
            "state": "NC",
        },
    ],
    "athens-ga": [
        {
            "name": "Downtown Athens",
            "slug": "downtown-athens-ga",
            "city": "Athens",
            "state": "GA",
        },
        {
            "name": "Normaltown",
            "slug": "normaltown-athens",
            "city": "Athens",
            "state": "GA",
        },
        {
            "name": "Five Points",
            "slug": "five-points-athens",
            "city": "Athens",
            "state": "GA",
        },
        {
            "name": "Boulevard",
            "slug": "boulevard-athens",
            "city": "Athens",
            "state": "GA",
        },
        {"name": "East Athens", "slug": "east-athens", "city": "Athens", "state": "GA"},
        {"name": "West Athens", "slug": "west-athens", "city": "Athens", "state": "GA"},
        {
            "name": "University of Georgia",
            "slug": "uga-campus-athens",
            "city": "Athens",
            "state": "GA",
        },
    ],
    "columbia-sc": [
        {
            "name": "Downtown Columbia",
            "slug": "downtown-columbia-sc",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "The Vista",
            "slug": "the-vista-columbia",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "Five Points",
            "slug": "five-points-columbia-sc",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "Shandon",
            "slug": "shandon-columbia",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "Forest Acres",
            "slug": "forest-acres-columbia",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "Rosewood",
            "slug": "rosewood-columbia",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "Earlewood",
            "slug": "earlewood-columbia",
            "city": "Columbia",
            "state": "SC",
        },
        {
            "name": "Heathwood",
            "slug": "heathwood-columbia",
            "city": "Columbia",
            "state": "SC",
        },
    ],
    "wilmington-nc": [
        {
            "name": "Downtown Wilmington",
            "slug": "downtown-wilmington-nc",
            "city": "Wilmington",
            "state": "NC",
        },
        {
            "name": "Historic District",
            "slug": "historic-wilmington-nc",
            "city": "Wilmington",
            "state": "NC",
        },
        {
            "name": "Wrightsville Beach",
            "slug": "wrightsville-beach",
            "city": "Wilmington",
            "state": "NC",
        },
        {
            "name": "Carolina Beach",
            "slug": "carolina-beach",
            "city": "Wilmington",
            "state": "NC",
        },
        {
            "name": "Kure Beach",
            "slug": "kure-beach",
            "city": "Wilmington",
            "state": "NC",
        },
        {
            "name": "Riverfront",
            "slug": "riverfront-wilmington",
            "city": "Wilmington",
            "state": "NC",
        },
        {
            "name": "College Road",
            "slug": "college-road-wilmington",
            "city": "Wilmington",
            "state": "NC",
        },
    ],
    "myrtle-beach-sc": [
        {
            "name": "Myrtle Beach Boardwalk",
            "slug": "myrtle-beach-boardwalk",
            "city": "Myrtle Beach",
            "state": "SC",
        },
        {
            "name": "Ocean Drive",
            "slug": "ocean-drive-myrtle-beach",
            "city": "Myrtle Beach",
            "state": "SC",
        },
        {
            "name": "The Market Common",
            "slug": "market-common-myrtle-beach",
            "city": "Myrtle Beach",
            "state": "SC",
        },
        {
            "name": "North Myrtle Beach",
            "slug": "north-myrtle-beach",
            "city": "Myrtle Beach",
            "state": "SC",
        },
        {
            "name": "Surfside Beach",
            "slug": "surfside-beach",
            "city": "Myrtle Beach",
            "state": "SC",
        },
        {
            "name": "Garden City Beach",
            "slug": "garden-city-beach",
            "city": "Myrtle Beach",
            "state": "SC",
        },
        {
            "name": "Murrells Inlet",
            "slug": "murrells-inlet",
            "city": "Myrtle Beach",
            "state": "SC",
        },
    ],
}

CITY_DESCRIPTIONS = {
    "GA": {
        "city": "Georgia's {city} offers a unique blend of Southern charm, rich history, and modern amenities. From historic downtown districts to beautiful natural surroundings, this city has something for everyone.",
        "town": "{city}, Georgia is a picturesque small town known for its tight-knit community, historic sites, and unique local character.",
    },
    "SC": {
        "city": "Welcome to {city}, South Carolina - a city steeped in Southern hospitality, rich history, and natural beauty. From stunning architecture to delicious local cuisine, experience the best of the Lowcountry.",
        "town": "{city}, South Carolina is a charming coastal town with a rich maritime heritage, beautiful beaches, and a welcoming community.",
    },
    "FL": {
        "city": "{city}, Florida boasts year-round sunshine, stunning beaches, and a vibrant cultural scene. From world-class dining to outdoor adventures, this city has it all.",
        "town": "{city}, Florida is a beloved coastal town known for its pristine beaches, water activities, and laid-back Florida lifestyle.",
    },
    "NC": {
        "city": "{city}, North Carolina combines mountain charm with urban sophistication. Explore beautiful neighborhoods, enjoy craft beer scene, and experience true Southern hospitality.",
        "town": "{city}, North Carolina is a scenic town nestled in the mountains or along the coast, offering outdoor adventures and small-town charm.",
    },
}

HIGHLIGHTS = {
    "GA": [
        "Historic Downtown",
        "Local Restaurants",
        "Community Parks",
        "Annual Festivals",
        "Farmers Markets",
    ],
    "SC": [
        "Historic Downtown",
        "Waterfront Views",
        "Southern Cuisine",
        "Art Galleries",
        "Beach Access",
    ],
    "FL": [
        "Beautiful Beaches",
        "Water Sports",
        "Fresh Seafood",
        "Vibrant Nightlife",
        "Year-round Sunshine",
    ],
    "NC": [
        "Mountain Views",
        "Craft Breweries",
        "Local Music",
        "Farm-to-Table Dining",
        "Outdoor Adventures",
    ],
}


def get_city_description(state, locality_type, city_name):
    key = state if state in CITY_DESCRIPTIONS else "GA"
    template = CITY_DESCRIPTIONS.get(key, CITY_DESCRIPTIONS["GA"]).get(
        locality_type, CITY_DESCRIPTIONS["GA"]["city"]
    )
    return template.format(city=city_name)


def get_highlights(state):
    key = state if state in HIGHLIGHTS else "GA"
    return HIGHLIGHTS[key]


def generate_image_url(slug, index=0):
    hash_val = sum(ord(c) for c in slug) + index
    return f"https://picsum.photos/seed/{hash_val}/800/600"


def create_locality(locality, locality_type_override=None):
    lt = locality_type_override or locality.get("localityType", "city")
    state = locality["state"]
    city = locality["city"]
    slug = locality["slug"]

    highlights = []
    for i, h in enumerate(get_highlights(state)[:3]):
        highlights.append(
            {
                "headline": h,
                "link": f"https://example.com/{slug}/{h.lower().replace(' ', '-')}",
                "imageUrl": generate_image_url(f"{slug}-{h}", i),
            }
        )

    return {
        "name": locality["name"],
        "slug": slug,
        "localityType": lt,
        "city": city,
        "state": state,
        "lat": locality["lat"],
        "lng": locality["lng"],
        "population": locality["population"],
        "imageUrl": generate_image_url(slug),
        "description": get_city_description(state, lt, city),
        "highlights": highlights,
        "timezone": "America/New_York",
    }


def create_neighborhood(neighborhood, city_slug, state):
    slug = neighborhood["slug"]
    return {
        "name": neighborhood["name"],
        "slug": slug,
        "localityType": "neighborhood",
        "city": neighborhood["city"],
        "state": neighborhood["state"],
        "lat": 33.0 + random.uniform(-0.5, 0.5),
        "lng": -81.0 + random.uniform(-0.5, 0.5),
        "population": random.randint(5000, 50000),
        "imageUrl": generate_image_url(slug),
        "description": f"{neighborhood['name']} is a vibrant neighborhood in {neighborhood['city']} with unique character, local shops, and community spirit.",
        "highlights": [
            {
                "headline": "Local Dining",
                "link": f"https://example.com/{slug}/dining",
                "imageUrl": generate_image_url(f"{slug}-dining", 1),
            },
            {
                "headline": "Community Events",
                "link": f"https://example.com/{slug}/events",
                "imageUrl": generate_image_url(f"{slug}-events", 2),
            },
            {
                "headline": "Parks & Recreation",
                "link": f"https://example.com/{slug}/parks",
                "imageUrl": generate_image_url(f"{slug}-parks", 3),
            },
        ],
        "timezone": "America/New_York",
    }


def main():
    all_localities = []
    communities = {}

    for city in CITIES:
        locality = create_locality(city)
        all_localities.append(locality)

        city_slug = city["slug"]
        if city_slug in NEIGHBORHOODS:
            communities[city_slug] = []
            for nh in NEIGHBORHOODS[city_slug]:
                communities[city_slug].append(
                    create_neighborhood(nh, city_slug, city["state"])
                )

    for town in TOWNS:
        locality = create_locality(town, "town")
        all_localities.append(locality)

    result = {"localities": all_localities, "communities": communities}

    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
