listenPort: 3003
database:
  host: db
  port: 5432
  username: postgres
  password: postgres
  database: ot_social
services:
  authentication:
    name: authentication
    transport: TCP
    host: authentication
    port: 3001
  profile:
    name: profile
    transport: TCP
    host: profile
    port: 3002
