// GENERATED by tools/mobile/generate-capacitor.mjs from the app registry — do not edit by hand.
export const APP_ENV = {
  mobile: true,
  apiBaseUrl: 'https://api.hopefulaspirationsindustries.com',
  socketUrl: 'https://towne-square.com',
  socketPath: '/socket.io',
};
