apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-processing-data
  namespace: optimistic-tanuki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: vultr-block-storage
