export const PersonaTelosCommands = {
  CREATE: 'PERSONA:CREATE',
  UPDATE: 'PERSONA:UPDATE',
  DELETE: 'PERSONA:DELETE',
  FIND: 'PERSONA:FIND',
  FIND_ONE: 'PERSONA:FIND_ONE',
};

export const ProfileTelosCommands = {
  CREATE: 'PROFILE:CREATE',
  UPDATE: 'PROFILE:UPDATE',
  DELETE: 'PROFILE:DELETE',
  FIND: 'PROFILE:FIND',
  FIND_ONE: 'PROFILE:FIND_ONE',
};

export const ProjectTelosCommands = {
  CREATE: 'PROJECT:CREATE',
  UPDATE: 'PROJECT:UPDATE',
  DELETE: 'PROJECT:DELETE',
  FIND: 'PROJECT:FIND',
  FIND_ONE: 'PROJECT:FIND_ONE',
};
