listenPort: 3009
database:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  username: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:postgres}
  database: ${POSTGRES_DB:store}
