# Set Error pages

# redirect all traffic to https
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 301 https://$host$request_uri;
    }
}

include /config/nginx/tanuki-upstream-host.inc;

# main server block for christopherrutherford.net
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name christopherrutherford.net;

    set $upstream_app $tanuki_upstream_host;
    set $upstream_port 8083;
    set $upstream_proto $tanuki_upstream_proto;

    include /config/nginx/tanuki-app-server.inc;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name experiments.christopherrutherford.net;

    set $upstream_app $tanuki_upstream_host;
    set $upstream_port 3000;
    set $upstream_proto $tanuki_upstream_proto;

    include /config/nginx/tanuki-app-server.inc;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name digital-homestead.christopherrutherford.net;

    set $upstream_app $tanuki_upstream_host;
    set $upstream_port 8082;
    set $upstream_proto $tanuki_upstream_proto;

    include /config/nginx/tanuki-app-server.inc;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name optimistic-tanuki.com;

    set $upstream_app $tanuki_upstream_host;
    set $upstream_port 8080;
    set $upstream_proto $tanuki_upstream_proto;
    set $ws_upstream_app $tanuki_upstream_host;
    set $ws_upstream_port 3301;
    set $ws_upstream_proto $tanuki_upstream_proto;

    include /config/nginx/tanuki-app-server-with-ws.inc;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name forgeofwill.com;

    set $upstream_app $tanuki_upstream_host;
    set $upstream_port 8081;
    set $upstream_proto $tanuki_upstream_proto;
    set $ws_upstream_app $tanuki_upstream_host;
    set $ws_upstream_port 3300;
    set $ws_upstream_proto $tanuki_upstream_proto;

    include /config/nginx/tanuki-app-server-with-ws.inc;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name towne-square.com;

    set $upstream_app $tanuki_upstream_host;
    set $upstream_port 8087;
    set $upstream_proto $tanuki_upstream_proto;
    set $ws_upstream_app $tanuki_upstream_host;
    set $ws_upstream_port 3300;
    set $ws_upstream_proto $tanuki_upstream_proto;

    include /config/nginx/tanuki-app-server-with-ws.inc;
}

# enable subdomain method reverse proxy confs
include /config/nginx/proxy-confs/*.subdomain.conf;
