export const AIOrchestrationCommands = {
    PROFILE_INITIALIZE: 'INITIALIZE_PROFILE',
    CONVERSATION_UPDATE: 'UPDATE_CONVERSATION',
    TELOS_UPDATE: 'UPDATE_TELOS',
    REFER_PERSONA: 'REFER_PERSONA',
}