const ChatCommands = {
  POST_MESSAGE: 'POST_MESSAGE',
  GET_CONVERSATIONS: 'GET_CONVERSATIONS',
  GET_CONVERSATION: 'GET_CONVERSATION',
  CREATE_COMMUNITY_CHAT: 'CREATE_COMMUNITY_CHAT',
  ADD_TO_COMMUNITY_CHAT: 'ADD_TO_COMMUNITY_CHAT',
  REMOVE_FROM_COMMUNITY_CHAT: 'REMOVE_FROM_COMMUNITY_CHAT',
  CREATE_ADDITIONAL_CHAT_ROOM: 'CREATE_ADDITIONAL_CHAT_ROOM',
};

export default ChatCommands;
