export const AccountCommands = {
  CREATE: 'CREATE_ACCOUNT',
  UPDATE: 'UPDATE_ACCOUNT',
  DELETE: 'DELETE_ACCOUNT',
  FIND: 'FIND_ACCOUNT',
  FIND_MANY: 'FIND_MANY_ACCOUNT',
};

export const TransactionCommands = {
  CREATE: 'CREATE_TRANSACTION',
  UPDATE: 'UPDATE_TRANSACTION',
  DELETE: 'DELETE_TRANSACTION',
  FIND: 'FIND_TRANSACTION',
  FIND_MANY: 'FIND_MANY_TRANSACTION',
};

export const InventoryItemCommands = {
  CREATE: 'CREATE_INVENTORY_ITEM',
  UPDATE: 'UPDATE_INVENTORY_ITEM',
  DELETE: 'DELETE_INVENTORY_ITEM',
  FIND: 'FIND_INVENTORY_ITEM',
  FIND_MANY: 'FIND_MANY_INVENTORY_ITEM',
};

export const BudgetCommands = {
  CREATE: 'CREATE_BUDGET',
  UPDATE: 'UPDATE_BUDGET',
  DELETE: 'DELETE_BUDGET',
  FIND: 'FIND_BUDGET',
  FIND_MANY: 'FIND_MANY_BUDGET',
};

export const RecurringItemCommands = {
  CREATE: 'CREATE_RECURRING_ITEM',
  UPDATE: 'UPDATE_RECURRING_ITEM',
  DELETE: 'DELETE_RECURRING_ITEM',
  FIND: 'FIND_RECURRING_ITEM',
  FIND_MANY: 'FIND_MANY_RECURRING_ITEM',
};

export const FinanceSummaryCommands = {
  GET_WORKSPACE_SUMMARY: 'GET_FINANCE_WORKSPACE_SUMMARY',
  GET_WORK_QUEUE: 'GET_FINANCE_WORK_QUEUE',
  GET_ONBOARDING_STATE: 'GET_FINANCE_ONBOARDING_STATE',
  BOOTSTRAP: 'BOOTSTRAP_FINANCE_WORKSPACES',
};

export const FinanceTenantCommands = {
  CREATE_TENANT: 'CREATE_FINANCE_TENANT',
  LIST_TENANTS: 'LIST_FINANCE_TENANTS',
  GET_CURRENT_TENANT: 'GET_FINANCE_CURRENT_TENANT',
  LIST_TENANT_MEMBERS: 'LIST_FINANCE_TENANT_MEMBERS',
};

export const FinanceBankingCommands = {
  CREATE_LINK_TOKEN: 'CREATE_FINANCE_BANK_LINK_TOKEN',
  EXCHANGE_PUBLIC_TOKEN: 'EXCHANGE_FINANCE_BANK_PUBLIC_TOKEN',
  CREATE_CONNECTION: 'CREATE_FINANCE_BANK_CONNECTION',
  LIST_CONNECTIONS: 'LIST_FINANCE_BANK_CONNECTIONS',
  SYNC_CONNECTION: 'SYNC_FINANCE_BANK_CONNECTION',
  DISCONNECT_CONNECTION: 'DISCONNECT_FINANCE_BANK_CONNECTION',
  PROCESS_WEBHOOK: 'PROCESS_FINANCE_BANK_WEBHOOK',
};
