export const AccountCommands = {
  CREATE: 'CREATE_ACCOUNT',
  UPDATE: 'UPDATE_ACCOUNT',
  DELETE: 'DELETE_ACCOUNT',
  FIND: 'FIND_ACCOUNT',
  FIND_MANY: 'FIND_MANY_ACCOUNT',
};

export const TransactionCommands = {
  CREATE: 'CREATE_TRANSACTION',
  UPDATE: 'UPDATE_TRANSACTION',
  DELETE: 'DELETE_TRANSACTION',
  FIND: 'FIND_TRANSACTION',
  FIND_MANY: 'FIND_MANY_TRANSACTION',
};

export const InventoryItemCommands = {
  CREATE: 'CREATE_INVENTORY_ITEM',
  UPDATE: 'UPDATE_INVENTORY_ITEM',
  DELETE: 'DELETE_INVENTORY_ITEM',
  FIND: 'FIND_INVENTORY_ITEM',
  FIND_MANY: 'FIND_MANY_INVENTORY_ITEM',
};

export const BudgetCommands = {
  CREATE: 'CREATE_BUDGET',
  UPDATE: 'UPDATE_BUDGET',
  DELETE: 'DELETE_BUDGET',
  FIND: 'FIND_BUDGET',
  FIND_MANY: 'FIND_MANY_BUDGET',
};
