export const TopicCommands = {
  CREATE: 'CREATE_TOPIC',
  UPDATE: 'UPDATE_TOPIC',
  DELETE: 'DELETE_TOPIC',
  FIND: 'FIND_TOPIC',
  FIND_MANY: 'FIND_MANY_TOPIC',
};

export const ThreadCommands = {
  CREATE: 'CREATE_THREAD',
  UPDATE: 'UPDATE_THREAD',
  DELETE: 'DELETE_THREAD',
  FIND: 'FIND_THREAD',
  FIND_MANY: 'FIND_MANY_THREAD',
};

export const ForumPostCommands = {
  CREATE: 'CREATE_FORUM_POST',
  UPDATE: 'UPDATE_FORUM_POST',
  DELETE: 'DELETE_FORUM_POST',
  FIND: 'FIND_FORUM_POST',
  FIND_MANY: 'FIND_MANY_FORUM_POST',
};

export const ForumLinkCommands = {
  CREATE: 'CREATE_FORUM_LINK',
  UPDATE: 'UPDATE_FORUM_LINK',
  DELETE: 'DELETE_FORUM_LINK',
  FIND: 'FIND_FORUM_LINK',
  FIND_MANY: 'FIND_MANY_FORUM_LINK',
};
