export const LearningCommands = {
  ListPrograms: 'learning.programs.list',
  SubmitAttempt: 'learning.attempts.submit',
  RecordEvaluation: 'learning.evaluations.record',
  GetAttempt: 'learning.attempts.get',
  GetCreditLedger: 'learning.credits.list',
  GetLesson: 'learning.lessons.get',
  GetProgress: 'learning.progress.get',
  SaveLessonProgress: 'learning.progress.save',
  RunCode: 'learning.code.run',
  GetDashboard: 'learning.dashboard.get',
  SubmitExercise: 'learning.exercises.submit',
  Enrol: 'learning.enrolments.create',
  Withdraw: 'learning.enrolments.withdraw',
  ListMyEnrolments: 'learning.enrolments.list',
};
