export const LearningCommands = {
  ListPrograms: 'learning.programs.list',
  ListCatalog: 'learning.catalog.list',
  ListSubjects: 'learning.subjects.list',
  SubmitAttempt: 'learning.attempts.submit',
  RecordEvaluation: 'learning.evaluations.record',
  GetAttempt: 'learning.attempts.get',
  GetCreditLedger: 'learning.credits.list',
  GetLesson: 'learning.lessons.get',
  GetOffering: 'learning.offerings.get',
  GetProgress: 'learning.progress.get',
  SaveLessonProgress: 'learning.progress.save',
  RunCode: 'learning.code.run',
  GetDashboard: 'learning.dashboard.get',
  SubmitExercise: 'learning.exercises.submit',
  Enrol: 'learning.enrolments.create',
  Withdraw: 'learning.enrolments.withdraw',
  ListMyEnrolments: 'learning.enrolments.list',
  ListMyOfferings: 'learning.offerings.mine.list',
  CreateOffering: 'learning.offerings.create',
  UpdateOffering: 'learning.offerings.update',
  DeleteOffering: 'learning.offerings.delete',
  GetOfferingOwnership: 'learning.offerings.ownership.get',
  SetCoEditors: 'learning.offerings.co-editors.set',
  SetOfferingStatus: 'learning.offerings.status.set',
};
