const ServiceTokens = {
    AUTHENTICATION_SERVICE: 'AUTHENTICATION_SERVICE',
    PROFILE_SERVICE: 'PROFILE_SERVICE',
    SOCIAL_SERVICE: 'SOCIAL_SERVICE',
    ASSETS_SERVICE: 'ASSETS_SERVICE',
    PROJECT_PLANNING_SERVICE: "PROJECT_PLANNING_SERVICE",
    CHAT_COLLECTOR_SERVICE: "CHAT_COLLECTOR_SERVICE",
    TELOS_DOCS_SERVICE: "TELOS_DOCS_SERVICE",
    AI_ORCHESTRATION_SERVICE: "AI_ORCHESTRATION_SERVICE",
    PROMPT_PROXY: "PROMPT_PROXY",
    BLOG_SERVICE: "BLOG_SERVICE",
}
export { ServiceTokens }