export const PostCommands = {
  CREATE: 'CREATE_POST',
  UPDATE: 'UPDATE_POST',
  DELETE: 'DELETE_POST',
  FIND: 'FIND_POST',
  FIND_MANY: 'FIND_MANY_POST',
};

export const VoteCommands = {
  GET: 'GET_VOTE',
  UPVOTE: 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE',
  UNVOTE: 'UNVOTE',
};

export const CommentCommands = {
  CREATE: 'CREATE_COMMENT',
  UPDATE: 'UPDATE_COMMENT',
  DELETE: 'DELETE_COMMENT',
  FIND: 'FIND_COMMENT',
  FIND_MANY: 'FIND_MANY_COMMENT',
};

export const LinkCommands = {
  CREATE: 'CREATE_LINK',
  UPDATE: 'UPDATE_LINK',
  DELETE: 'DELETE_LINK',
  FIND: 'FIND_LINK',
  FIND_MANY: 'FIND_MANY_LINK',
};

export const AttachmentCommands = {
  CREATE: 'CREATE_ATTACHMENT',
  UPDATE: 'UPDATE_ATTACHMENT',
  DELETE: 'DELETE_ATTACHMENT',
  FIND: 'FIND_ATTACHMENT',
  FIND_MANY: 'FIND_MANY_ATTACHMENT',
};

export const FollowCommands = {
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  GET_FOLLOWING: 'GET_FOLLOWING',
  GET_MUTUALS: 'GET_MUTUALS',
  GET_FOLLOWER_COUNT: 'GET_FOLLOWER_COUNT',
  GET_FOLLOWING_COUNT: 'GET_FOLLOWING_COUNT',
};

export const SocialComponentCommands = {
  CREATE: 'CREATE_SOCIAL_COMPONENT',
  UPDATE: 'UPDATE_SOCIAL_COMPONENT',
  DELETE: 'DELETE_SOCIAL_COMPONENT',
  FIND: 'FIND_SOCIAL_COMPONENT',
  FIND_BY_POST: 'FIND_SOCIAL_COMPONENTS_BY_POST',
  DELETE_BY_POST: 'DELETE_SOCIAL_COMPONENTS_BY_POST',
  FIND_BY_QUERY: 'FIND_SOCIAL_COMPONENTS_BY_QUERY',
};

export const SocialRealtimeCommands = {
  SUBSCRIBE_POSTS: 'SUBSCRIBE_POSTS',
  UNSUBSCRIBE_POSTS: 'UNSUBSCRIBE_POSTS',
  SUBSCRIBE_USER_ACTIVITY: 'SUBSCRIBE_USER_ACTIVITY',
  UNSUBSCRIBE_USER_ACTIVITY: 'UNSUBSCRIBE_USER_ACTIVITY',
  GET_FEED: 'GET_FEED',
  GET_FOLLOWING: 'GET_FOLLOWING',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
};
