export const PostCommands = {
  CREATE: 'CREATE_POST',
  UPDATE: 'UPDATE_POST',
  DELETE: 'DELETE_POST',
  FIND: 'FIND_POST',
  FIND_MANY: 'FIND_MANY_POST',
};

export const VoteCommands = {
  GET: 'GET_VOTE',
  UPVOTE: 'UPVOTE',
  DOWNVOTE: 'DOWNVOTE',
  UNVOTE: 'UNVOTE',
};

export const ReactionCommands = {
  ADD: 'ADD_REACTION',
  REMOVE: 'REMOVE_REACTION',
  GET: 'GET_REACTION',
  GET_BY_POST: 'GET_REACTIONS_BY_POST',
  GET_BY_COMMENT: 'GET_REACTIONS_BY_COMMENT',
  GET_USER_REACTION: 'GET_USER_REACTION',
};

export const CommentCommands = {
  CREATE: 'CREATE_COMMENT',
  UPDATE: 'UPDATE_COMMENT',
  DELETE: 'DELETE_COMMENT',
  FIND: 'FIND_COMMENT',
  FIND_MANY: 'FIND_MANY_COMMENT',
};

export const LinkCommands = {
  CREATE: 'CREATE_LINK',
  UPDATE: 'UPDATE_LINK',
  DELETE: 'DELETE_LINK',
  FIND: 'FIND_LINK',
  FIND_MANY: 'FIND_MANY_LINK',
};

export const AttachmentCommands = {
  CREATE: 'CREATE_ATTACHMENT',
  UPDATE: 'UPDATE_ATTACHMENT',
  DELETE: 'DELETE_ATTACHMENT',
  FIND: 'FIND_ATTACHMENT',
  FIND_MANY: 'FIND_MANY_ATTACHMENT',
};

export const FollowCommands = {
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  GET_FOLLOWING: 'GET_FOLLOWING',
  GET_MUTUALS: 'GET_MUTUALS',
  GET_FOLLOWER_COUNT: 'GET_FOLLOWER_COUNT',
  GET_FOLLOWING_COUNT: 'GET_FOLLOWING_COUNT',
};

export const SocialComponentCommands = {
  CREATE: 'CREATE_SOCIAL_COMPONENT',
  UPDATE: 'UPDATE_SOCIAL_COMPONENT',
  DELETE: 'DELETE_SOCIAL_COMPONENT',
  FIND: 'FIND_SOCIAL_COMPONENT',
  FIND_BY_POST: 'FIND_SOCIAL_COMPONENTS_BY_POST',
  DELETE_BY_POST: 'DELETE_SOCIAL_COMPONENTS_BY_POST',
  FIND_BY_QUERY: 'FIND_SOCIAL_COMPONENTS_BY_QUERY',
};

export const SocialRealtimeCommands = {
  SUBSCRIBE_POSTS: 'SUBSCRIBE_POSTS',
  UNSUBSCRIBE_POSTS: 'UNSUBSCRIBE_POSTS',
  SUBSCRIBE_USER_ACTIVITY: 'SUBSCRIBE_USER_ACTIVITY',
  UNSUBSCRIBE_USER_ACTIVITY: 'UNSUBSCRIBE_USER_ACTIVITY',
  SUBSCRIBE_NOTIFICATIONS: 'SUBSCRIBE_NOTIFICATIONS',
  UNSUBSCRIBE_NOTIFICATIONS: 'UNSUBSCRIBE_NOTIFICATIONS',
  GET_FEED: 'GET_FEED',
  GET_FOLLOWING: 'GET_FOLLOWING',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  BROADCAST_NOTIFICATION: 'BROADCAST_NOTIFICATION',
};

export const CommunityCommands = {
  CREATE: 'CREATE_COMMUNITY',
  UPDATE: 'UPDATE_COMMUNITY',
  DELETE: 'DELETE_COMMUNITY',
  FIND: 'FIND_COMMUNITY',
  FIND_MANY: 'FIND_MANY_COMMUNITY',
  GET_TOP_ACTIVE: 'GET_TOP_ACTIVE_COMMUNITY',
  JOIN: 'JOIN_COMMUNITY',
  LEAVE: 'LEAVE_COMMUNITY',
  GET_MEMBERS: 'GET_COMMUNITY_MEMBERS',
  GET_USER_COMMUNITIES: 'GET_USER_COMMUNITIES',
  INVITE: 'INVITE_TO_COMMUNITY',
  REMOVE_MEMBER: 'REMOVE_COMMUNITY_MEMBER',
  APPROVE_MEMBER: 'APPROVE_COMMUNITY_MEMBER',
  REJECT_MEMBER: 'REJECT_COMMUNITY_MEMBER',
  GET_PENDING_INVITES: 'GET_PENDING_INVITES',
  GET_PENDING_JOIN_REQUESTS: 'GET_PENDING_JOIN_REQUESTS',
  CANCEL_INVITE: 'CANCEL_INVITE',
  GET_FEED: 'GET_COMMUNITY_FEED',
};

export const NotificationCommands = {
  CREATE: 'CREATE_NOTIFICATION',
  FIND: 'FIND_NOTIFICATION',
  FIND_BY_RECIPIENT: 'FIND_NOTIFICATIONS_BY_RECIPIENT',
  MARK_READ: 'MARK_NOTIFICATION_READ',
  MARK_ALL_READ: 'MARK_ALL_NOTIFICATIONS_READ',
  DELETE: 'DELETE_NOTIFICATION',
  GET_UNREAD_COUNT: 'GET_UNREAD_NOTIFICATION_COUNT',
};

export const PrivacyCommands = {
  BLOCK_USER: 'BLOCK_USER',
  UNBLOCK_USER: 'UNBLOCK_USER',
  GET_BLOCKED_USERS: 'GET_BLOCKED_USERS',
  IS_USER_BLOCKED: 'IS_USER_BLOCKED',
  MUTE_USER: 'MUTE_USER',
  UNMUTE_USER: 'UNMUTE_USER',
  GET_MUTED_USERS: 'GET_MUTED_USERS',
  REPORT_CONTENT: 'REPORT_CONTENT',
  GET_MY_REPORTS: 'GET_MY_REPORTS',
};

export const SearchCommands = {
  SEARCH: 'SEARCH',
  GET_TRENDING: 'GET_TRENDING_SEARCH',
  GET_SUGGESTED_USERS: 'GET_SUGGESTED_USERS',
  GET_SUGGESTED_COMMUNITIES: 'GET_SUGGESTED_COMMUNITIES',
  GET_SEARCH_HISTORY: 'GET_SEARCH_HISTORY',
};

export const ActivityCommands = {
  CREATE: 'CREATE_ACTIVITY',
  FIND: 'FIND_ACTIVITY',
  FIND_BY_PROFILE: 'FIND_ACTIVITIES_BY_PROFILE',
  DELETE: 'DELETE_ACTIVITY',
};

export const SavedItemCommands = {
  SAVE: 'SAVE_ITEM',
  UNSAVE: 'UNSAVE_ITEM',
  FIND_SAVED: 'FIND_SAVED_ITEMS',
  IS_SAVED: 'IS_ITEM_SAVED',
};

export const PresenceCommands = {
  SET_PRESENCE: 'SET_PRESENCE',
  GET_PRESENCE: 'GET_PRESENCE',
  GET_PRESENCE_BATCH: 'GET_PRESENCE_BATCH',
  GET_ONLINE_USERS: 'GET_ONLINE_USERS',
  UPDATE_LAST_SEEN: 'UPDATE_LAST_SEEN',
  SET_OFFLINE: 'SET_OFFLINE',
};

export const ProfileAnalyticsCommands = {
  RECORD_VIEW: 'RECORD_PROFILE_VIEW',
  GET_VIEW_STATS: 'GET_PROFILE_VIEW_STATS',
  GET_RECENT_VIEWERS: 'GET_RECENT_PROFILE_VIEWERS',
};

export const PollCommands = {
  CREATE: 'CREATE_POLL',
  UPDATE: 'UPDATE_POLL',
  DELETE: 'DELETE_POLL',
  FIND: 'FIND_POLL',
  FIND_MANY: 'FIND_MANY_POLL',
  VOTE: 'VOTE_POLL',
  REMOVE_VOTE: 'REMOVE_VOTE_POLL',
};

export const PostShareCommands = {
  CREATE: 'CREATE_POST_SHARE',
  DELETE: 'DELETE_POST_SHARE',
  FIND_BY_POST: 'FIND_POST_SHARES_BY_POST',
  FIND_BY_PROFILE: 'FIND_POST_SHARES_BY_PROFILE',
};

export const EventCommands = {
  CREATE: 'CREATE_EVENT',
  UPDATE: 'UPDATE_EVENT',
  DELETE: 'DELETE_EVENT',
  FIND: 'FIND_EVENT',
  FIND_MANY: 'FIND_MANY_EVENT',
  FIND_UPCOMING: 'FIND_UPCOMING_EVENTS',
  ATTEND: 'ATTEND_EVENT',
  UNATTEND: 'UNATTEND_EVENT',
  IS_ATTENDING: 'IS_ATTENDING_EVENT',
};

export const ScheduledPostCommands = {
  CREATE: 'CREATE_SCHEDULED_POST',
  UPDATE: 'UPDATE_SCHEDULED_POST',
  DELETE: 'DELETE_SCHEDULED_POST',
  FIND: 'FIND_SCHEDULED_POST',
  FIND_MANY: 'FIND_MANY_SCHEDULED_POST',
  PUBLISH: 'PUBLISH_SCHEDULED_POST',
};
