// GENERATED by tools/mobile/generate-capacitor.mjs from the app registry — do not edit by hand.
export const APP_ENV = {
  mobile: true,
  apiBaseUrl: 'https://forgeofwill.com/api',
  socketUrl: 'https://forgeofwill.com',
  socketPath: '/socket.io',
};
