listenPort: 3025
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: audio_workstation
services:
  assets:
    transport: 0
    options: {}
    host: assets
    port: 3005
  ai_orchestrator:
    transport: 0
    options: {}
    host: ai-orchestrator
    port: 3010
