#!/bin/bash

# Generate a features breakdown report based on captured screenshots
# This script analyzes the screenshot directory structure and generates a markdown report

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$( cd "$SCRIPT_DIR/../.." && pwd )"
SCREENSHOTS_DIR="$ROOT_DIR/screenshots"
REPORT_FILE="$ROOT_DIR/FEATURES_BREAKDOWN.md"

echo "==================================="
echo "Generating Features Breakdown"
echo "==================================="
echo ""

if [ ! -d "$SCREENSHOTS_DIR" ]; then
  echo "Error: Screenshots directory not found at $SCREENSHOTS_DIR"
  echo "Please run the screenshot capture script first."
  exit 1
fi

# Start the report
cat > "$REPORT_FILE" << 'EOF'
# Angular Applications Features Breakdown

This document provides an overview of the features and screens available in each Angular application, based on automated screenshot capture.

**Generated**: $(date)

---

EOF

# Function to get screen count for an app
count_screens() {
  local app_dir=$1
  if [ -d "$app_dir" ]; then
    # Count unique screen names (without viewport suffix)
    find "$app_dir" -name "*.png" -exec basename {} \; | sed 's/-desktop\.png//;s/-tablet\.png//;s/-mobile\.png//' | sort -u | wc -l
  else
    echo "0"
  fi
}

# Function to list screens for an app
list_screens() {
  local app_dir=$1
  if [ -d "$app_dir" ]; then
    find "$app_dir" -name "*-desktop.png" -exec basename {} \; | sed 's/-desktop\.png//' | sort
  fi
}

# Function to generate app section
generate_app_section() {
  local app_name=$1
  local app_display_name=$2
  local app_dir="$SCREENSHOTS_DIR/$app_name"
  local app_port=$3
  
  if [ ! -d "$app_dir" ]; then
    echo "⚠️  No screenshots found for $app_display_name"
    return
  fi
  
  local screen_count=$(count_screens "$app_dir")
  
  cat >> "$REPORT_FILE" << EOF

## $app_display_name

**Application**: \`$app_name\`
**Port**: $app_port
**Total Screens**: $screen_count

### Screens Captured

EOF

  # List all unique screens
  local screens=$(list_screens "$app_dir")
  
  if [ -z "$screens" ]; then
    echo "No screens found" >> "$REPORT_FILE"
  else
    echo "$screens" | while read -r screen; do
      echo "- **$screen**" >> "$REPORT_FILE"
      
      # Add viewport indicators
      local has_desktop=$([ -f "$app_dir/${screen}-desktop.png" ] && echo "✓" || echo "")
      local has_tablet=$([ -f "$app_dir/${screen}-tablet.png" ] && echo "✓" || echo "")
      local has_mobile=$([ -f "$app_dir/${screen}-mobile.png" ] && echo "✓" || echo "")
      
      echo "  - Responsive: Desktop $has_desktop | Tablet $has_tablet | Mobile $has_mobile" >> "$REPORT_FILE"
      echo "" >> "$REPORT_FILE"
    done
  fi
  
  echo "" >> "$REPORT_FILE"
  echo "### Screenshot Locations" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "Screenshots for this application are located in:" >> "$REPORT_FILE"
  echo "\`screenshots/$app_name/\`" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
}

# Generate sections for each app
echo "Analyzing client-interface..."
generate_app_section "client-interface" "Client Interface" "4200"

echo "Analyzing forgeofwill..."
generate_app_section "forgeofwill" "Forge of Will" "4201"

echo "Analyzing christopherrutherford-net..."
generate_app_section "christopherrutherford-net" "Christopher Rutherford Net" "4202"

echo "Analyzing digital-homestead..."
generate_app_section "digital-homestead" "Digital Homestead" "4203"

# Add summary section
cat >> "$REPORT_FILE" << 'EOF'

---

## Summary

EOF

# Count totals
TOTAL_APPS=$(find "$SCREENSHOTS_DIR" -mindepth 1 -maxdepth 1 -type d | wc -l)
TOTAL_SCREENSHOTS=$(find "$SCREENSHOTS_DIR" -name "*.png" | wc -l)

cat >> "$REPORT_FILE" << EOF
- **Total Applications Analyzed**: $TOTAL_APPS
- **Total Screenshots Captured**: $TOTAL_SCREENSHOTS
- **Viewports Tested**: Desktop (1920x1080), Tablet (768x1024), Mobile (375x667)
- **Browser Used**: Chrome (Chromium)

## How to Use This Report

This features breakdown was generated automatically based on the application routes and screenshot captures. To get more detailed information about each screen:

1. Review the actual screenshots in the \`screenshots/\` directory
2. Check the application route definitions in each app's \`app.routes.ts\` file
3. Examine the component code to understand the features implemented

## Updating This Report

To regenerate this report after capturing new screenshots:

\`\`\`bash
cd tools/screenshots
./generate-features-report.sh
\`\`\`

---

*This report was automatically generated by the screenshot capture tool.*
EOF

echo ""
echo "✓ Features breakdown report generated!"
echo ""
echo "Report saved to: $REPORT_FILE"
echo ""
