listenPort: 3004
database:
  host: db
  port: 5432
  username: postgres
  password: postgres
  database: ot_payments
services:
  profile:
    name: profile
    transport: TCP
    host: ot_profile
    port: 3002
lemonSqueezy:
  default:
    apiKey: ''
    storeId: ''
  stores: {}
