FROM docker.io/node:24-alpine AS base
RUN apk add --no-cache libc6-compat dumb-init
WORKDIR /usr/src/app

# Install dependencies
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY tsconfig*.json ./
COPY nx.json ./
COPY eslint.config.mjs .
COPY libs ./libs
COPY apps/gateway ./apps/gateway
RUN corepack enable && corepack prepare pnpm@11.0.9 --activate && pnpm install --frozen-lockfile

# Build the app with sourcemaps (development configuration)
RUN pnpm exec nx build gateway --configuration development --verbose

# Production image
FROM docker.io/node:24-alpine AS runner
RUN apk add --no-cache dumb-init
ENV NODE_ENV=development
ENV PORT=3000
WORKDIR /usr/src/app
COPY --from=base /usr/src/app/node_modules ./node_modules
COPY --from=base /usr/src/app/dist/apps/gateway ./dist/apps/gateway
COPY --from=base /usr/src/app/package.json ./package.json
RUN corepack enable && corepack prepare pnpm@11.0.9 --activate && pnpm add -w nodemon

USER node
EXPOSE 3000
CMD ["dumb-init", "node", "dist/apps/gateway/main.js"]
