FROM docker.io/node:lts-alpine AS base
RUN apk add --no-cache libc6-compat dumb-init
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
COPY tsconfig*.json ./
COPY nx.json ./
COPY eslint.config.mjs .
COPY libs ./libs
COPY apps/gateway ./apps/gateway
RUN npm install --legacy-peer-deps

# Build the app with sourcemaps (development configuration)
RUN npx nx build gateway --configuration development --verbose

# Production image
FROM docker.io/node:lts-alpine AS runner
RUN apk add --no-cache dumb-init
ENV NODE_ENV=development
ENV PORT=3000
WORKDIR /usr/src/app
RUN npm i -g nodemon
COPY --from=base /usr/src/app/node_modules ./node_modules
COPY --from=base /usr/src/app/dist/apps/gateway ./dist/apps/gateway
COPY --from=base /usr/src/app/package.json ./package.json

USER node
EXPOSE 3000
CMD ["dumb-init", "node", "dist/apps/gateway/main.js"]
