import { Injectable } from '@nestjs/common';
import { Component, ComponentType } from '@optimistic-tanuki/models';

const COMPONENT_CATALOG: Component[] = [
  {
    id: 'cpu-pi5',
    type: ComponentType.CPU,
    name: 'Raspberry Pi 5 (4-core)',
    description: 'Broadcom BCM2712 4-core ARM Cortex-A76 at 2.4GHz',
    basePrice: 0,
    sellingPrice: 0,
    specs: { cores: 4, frequency: '2.4GHz', architecture: 'ARM64' },
    compatibleWith: ['xs-cloud', 'xs-nas'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cpu-n100',
    type: ComponentType.CPU,
    name: 'Intel N100',
    description: 'Intel Alder Lake-N quad-core processor',
    basePrice: 89.99,
    sellingPrice: 103.49,
    specs: { cores: 4, frequency: '3.4GHz', architecture: 'x86_64', tdp: '6W' },
    compatibleWith: ['s-cloud', 's-dev', 'm-hybrid'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cpu-i3-12100',
    type: ComponentType.CPU,
    name: 'Intel Core i3-12100',
    description: '12th Gen quad-core processor for desktop workloads',
    basePrice: 139.99,
    sellingPrice: 160.99,
    specs: {
      cores: 4,
      frequency: '4.3GHz',
      architecture: 'x86_64',
      tdp: '60W',
    },
    compatibleWith: ['m-hybrid', 'm-enterprise', 'l-enterprise'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cpu-i5-12400',
    type: ComponentType.CPU,
    name: 'Intel Core i5-12400',
    description: '6-core processor for demanding workloads',
    basePrice: 199.99,
    sellingPrice: 229.99,
    specs: {
      cores: 6,
      frequency: '4.4GHz',
      architecture: 'x86_64',
      tdp: '65W',
    },
    compatibleWith: ['m-enterprise', 'l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cpu-i7-12700',
    type: ComponentType.CPU,
    name: 'Intel Core i7-12700',
    description: 'High-performance 12-core processor',
    basePrice: 349.99,
    sellingPrice: 402.49,
    specs: {
      cores: 12,
      frequency: '4.9GHz',
      architecture: 'x86_64',
      tdp: '65W',
    },
    compatibleWith: ['l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ram-4gb',
    type: ComponentType.RAM,
    name: '4GB DDR4 SODIMM',
    description: '4GB DDR4-3200MHz memory module',
    basePrice: 29.99,
    sellingPrice: 35.99,
    specs: { capacity: '4GB', type: 'DDR4', speed: '3200MHz' },
    compatibleWith: ['xs-cloud', 'xs-nas'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ram-8gb',
    type: ComponentType.RAM,
    name: '8GB DDR4 SODIMM',
    description: '8GB DDR4-3200MHz memory module',
    basePrice: 49.99,
    sellingPrice: 59.99,
    specs: { capacity: '8GB', type: 'DDR4', speed: '3200MHz' },
    compatibleWith: ['xs-cloud', 'xs-nas', 's-cloud', 's-dev', 'm-hybrid'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ram-16gb',
    type: ComponentType.RAM,
    name: '16GB DDR4 SODIMM',
    description: '16GB DDR4-3200MHz memory module',
    basePrice: 79.99,
    sellingPrice: 95.99,
    specs: { capacity: '16GB', type: 'DDR4', speed: '3200MHz' },
    compatibleWith: ['s-cloud', 's-dev', 'm-hybrid', 'm-enterprise'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ram-32gb',
    type: ComponentType.RAM,
    name: '32GB DDR4 DIMM',
    description: '32GB DDR4-3200MHz desktop memory',
    basePrice: 139.99,
    sellingPrice: 167.99,
    specs: { capacity: '32GB', type: 'DDR4', speed: '3200MHz' },
    compatibleWith: ['m-hybrid', 'm-enterprise', 'l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ram-64gb',
    type: ComponentType.RAM,
    name: '64GB DDR4 DIMM',
    description: '64GB DDR4-3200MHz server-grade memory',
    basePrice: 249.99,
    sellingPrice: 299.99,
    specs: { capacity: '64GB', type: 'DDR4', speed: '3200MHz', ecc: 'false' },
    compatibleWith: ['l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'storage-256gb-nvme',
    type: ComponentType.STORAGE,
    name: '256GB NVMe SSD',
    description: 'M.2 NVMe Gen3 SSD',
    basePrice: 39.99,
    sellingPrice: 49.99,
    specs: { capacity: '256GB', type: 'NVMe', readSpeed: '2000MB/s' },
    compatibleWith: [
      'xs-cloud',
      'xs-nas',
      's-cloud',
      's-dev',
      'm-hybrid',
      'm-enterprise',
      'l-enterprise',
      'l-cloud',
    ],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'storage-512gb-nvme',
    type: ComponentType.STORAGE,
    name: '512GB NVMe SSD',
    description: 'M.2 NVMe Gen3 SSD',
    basePrice: 59.99,
    sellingPrice: 74.99,
    specs: { capacity: '512GB', type: 'NVMe', readSpeed: '3000MB/s' },
    compatibleWith: [
      'xs-cloud',
      'xs-nas',
      's-cloud',
      's-dev',
      'm-hybrid',
      'm-enterprise',
      'l-enterprise',
      'l-cloud',
    ],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'storage-1tb-nvme',
    type: ComponentType.STORAGE,
    name: '1TB NVMe SSD',
    description: 'M.2 NVMe Gen4 SSD',
    basePrice: 89.99,
    sellingPrice: 112.49,
    specs: { capacity: '1TB', type: 'NVMe', readSpeed: '5000MB/s' },
    compatibleWith: [
      's-cloud',
      's-dev',
      'm-hybrid',
      'm-enterprise',
      'l-enterprise',
      'l-cloud',
    ],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'storage-2tb-nvme',
    type: ComponentType.STORAGE,
    name: '2TB NVMe SSD',
    description: 'M.2 NVMe Gen4 SSD',
    basePrice: 149.99,
    sellingPrice: 187.49,
    specs: { capacity: '2TB', type: 'NVMe', readSpeed: '7000MB/s' },
    compatibleWith: [
      's-cloud',
      's-dev',
      'm-hybrid',
      'm-enterprise',
      'l-enterprise',
      'l-cloud',
    ],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'storage-4tb-hdd',
    type: ComponentType.STORAGE,
    name: '4TB HDD',
    description: '4TB 3.5" HDD for bulk storage',
    basePrice: 79.99,
    sellingPrice: 99.99,
    specs: { capacity: '4TB', type: 'HDD', rpm: '5400' },
    compatibleWith: ['xs-nas', 'm-hybrid', 'l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'storage-8tb-hdd',
    type: ComponentType.STORAGE,
    name: '8TB HDD',
    description: '8TB 3.5" HDD for mass storage',
    basePrice: 149.99,
    sellingPrice: 187.49,
    specs: { capacity: '8TB', type: 'HDD', rpm: '7200' },
    compatibleWith: ['m-hybrid', 'l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpu-none',
    type: ComponentType.GPU,
    name: 'Integrated Graphics',
    description: 'Use onboard graphics (no discrete GPU)',
    basePrice: 0,
    sellingPrice: 0,
    specs: { type: 'integrated', vram: '0' },
    compatibleWith: [
      'xs-cloud',
      'xs-nas',
      's-cloud',
      's-dev',
      'm-hybrid',
      'm-enterprise',
      'l-enterprise',
      'l-cloud',
    ],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpu-t400',
    type: ComponentType.GPU,
    name: 'NVIDIA T400',
    description: 'Entry-level professional GPU',
    basePrice: 249.99,
    sellingPrice: 287.49,
    specs: { vram: '2GB', type: 'discrete', tdp: '30W' },
    compatibleWith: ['s-dev', 'm-hybrid', 'm-enterprise', 'l-enterprise'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpu-gtx-1650',
    type: ComponentType.GPU,
    name: 'NVIDIA GTX 1650',
    description: 'Mid-range GPU for light gaming and ML',
    basePrice: 179.99,
    sellingPrice: 206.99,
    specs: { vram: '4GB', type: 'discrete', tdp: '75W' },
    compatibleWith: ['s-dev', 'm-hybrid', 'l-enterprise'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpu-rtx-3050',
    type: ComponentType.GPU,
    name: 'NVIDIA RTX 3050',
    description: 'Entry-level RTX GPU with ray tracing',
    basePrice: 249.99,
    sellingPrice: 287.49,
    specs: { vram: '8GB', type: 'discrete', tdp: '130W', rayTracing: 'true' },
    compatibleWith: ['m-hybrid', 'l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpu-rtx-4060',
    type: ComponentType.GPU,
    name: 'NVIDIA RTX 4060',
    description: 'Mid-range RTX GPU for AI/ML workloads',
    basePrice: 399.99,
    sellingPrice: 459.99,
    specs: { vram: '8GB', type: 'discrete', tdp: '115W', rayTracing: 'true' },
    compatibleWith: ['l-enterprise', 'l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpu-rtx-4090',
    type: ComponentType.GPU,
    name: 'NVIDIA RTX 4090',
    description: 'High-end GPU for intensive AI/ML workloads',
    basePrice: 1599.99,
    sellingPrice: 1839.99,
    specs: { vram: '24GB', type: 'discrete', tdp: '450W', rayTracing: 'true' },
    compatibleWith: ['l-cloud'],
    inStock: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

@Injectable()
export class ComponentsService {
  async findAll(type: string, chassisId?: string): Promise<Component[]> {
    let components = COMPONENT_CATALOG.filter((c) => c.isActive && c.inStock);

    if (type) {
      components = components.filter((c) => c.type === type);
    }

    if (chassisId) {
      components = components.filter((c) =>
        c.compatibleWith.includes(chassisId)
      );
    }

    return components;
  }

  async findById(id: string): Promise<Component | undefined> {
    return COMPONENT_CATALOG.find((c) => c.id === id && c.isActive);
  }
}
