export const ProfileTelosCommands = {
  CREATE: 'PROFILE:CREATE',
  UPDATE: 'PROFILE:UPDATE',
  DELETE: 'PROFILE:DELETE',
  RESET_DERIVED: 'PROFILE:RESET_DERIVED',
  FIND: 'PROFILE:FIND',
  FIND_ONE: 'PROFILE:FIND_ONE',
  FIND_BY_PROFILE_ID: 'PROFILE:FIND_BY_PROFILE_ID',
  UPSERT_SOURCE: 'PROFILE:UPSERT_SOURCE',
  REGENERATE: 'PROFILE:REGENERATE',
};
