// GENERATED by tools/mobile/generate-capacitor.mjs from the app registry — do not edit by hand.
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.optimistictanuki.app',
  appName: 'Optimistic Tanuki',
  webDir: '../../dist/apps/client-interface/browser',
  server: {
    androidScheme: 'https',
    // Dev-mode live reload: point the webview at a dev server instead of bundled assets.
    ...(process.env['CAP_SERVER_URL']
      ? { url: process.env['CAP_SERVER_URL'], cleartext: true }
      : {}),
  },
};

export default config;
