apiVersion: apps/v1
kind: Deployment
metadata:
  name: d6
  namespace: optimistic-tanuki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d6
  template:
    metadata:
      labels:
        app: d6
    spec:
      containers:
        - name: d6
          image: cjrutherford/optimistic_tanuki_d6:sha-1d12c7afda88e22db8371f88f9923913309b6638
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '4000'
            - name: GATEWAY_URL
              value: 'http://gateway:3000'
          resources:
            requests:
              memory: '64Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '250m'
          livenessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: d6
  namespace: optimistic-tanuki
spec:
  selector:
    app: d6
  ports:
    - port: 8086
      targetPort: 4000
  type: LoadBalancer
