import { AppRegistry } from './app-registry.types';

const API_BASE_URL = 'https://api.haidev.com';

export const DEFAULT_APP_REGISTRY: AppRegistry = {
  version: '1.0.0',
  generatedAt: '2026-04-22T00:00:00.000Z',
  apps: [
    {
      appId: 'hai',
      name: 'HAI Company Website',
      domain: 'haidev.com',
      uiBaseUrl: 'https://haidev.com',
      apiBaseUrl: API_BASE_URL,
      appType: 'client',
      visibility: 'public',
      description: 'Company website and HAI ecosystem entry point.',
      sortOrder: 1,
    },
    {
      appId: 'system-configurator',
      name: 'HAI Computer',
      domain: 'haicomputer.com',
      uiBaseUrl: 'https://haicomputer.com',
      apiBaseUrl: API_BASE_URL,
      appType: 'client',
      visibility: 'public',
      description: 'Build-to-order personal cloud and homelab configurator.',
      sortOrder: 2,
    },
    {
      appId: 'store',
      name: 'HAI Store',
      domain: 'haidev.com',
      subdomain: 'store',
      uiBaseUrl: 'https://store.haidev.com',
      apiBaseUrl: API_BASE_URL,
      appType: 'client',
      visibility: 'public',
      description: 'Public store for HAI products and services.',
      sortOrder: 3,
    },
    {
      appId: 'opportunity-compass',
      name: 'Opportunity Compass',
      domain: 'haidev.com',
      subdomain: 'opportunities',
      uiBaseUrl: 'https://opportunities.haidev.com',
      apiBaseUrl: API_BASE_URL,
      appType: 'client',
      visibility: 'public',
      description: 'Opportunity discovery from interests, locality, and skills.',
      sortOrder: 4,
    },
    {
      appId: 'owner-console',
      name: 'Owner Console',
      domain: 'haidev.com',
      subdomain: 'owner',
      uiBaseUrl: 'https://owner.haidev.com',
      apiBaseUrl: API_BASE_URL,
      appType: 'admin',
      visibility: 'internal',
      description: 'Internal HAI operator console.',
      sortOrder: 100,
    },
  ],
};
