apiVersion: v1
kind: Secret
metadata:
  name: gateway-oauth-secrets
  namespace: optimistic-tanuki
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: ''
  GOOGLE_CLIENT_SECRET: ''
  GOOGLE_REDIRECT_URI: https://optimistic-tanuki.com/oauth/callback/google
  GITHUB_CLIENT_ID: ''
  GITHUB_CLIENT_SECRET: ''
  GITHUB_REDIRECT_URI: https://optimistic-tanuki.com/oauth/callback/github
  MICROSOFT_CLIENT_ID: ''
  MICROSOFT_CLIENT_SECRET: ''
  MICROSOFT_REDIRECT_URI: https://optimistic-tanuki.com/oauth/callback/microsoft
  FACEBOOK_CLIENT_ID: ''
  FACEBOOK_CLIENT_SECRET: ''
  FACEBOOK_REDIRECT_URI: https://optimistic-tanuki.com/oauth/callback/facebook
