apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: optimistic-tanuki

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - seaweedfs.yaml
  - gateway.yaml
  - assets.yaml
  - services/
  - clients/
  - ingress.yaml
  - ../secrets/secrets.yaml
