listenPort: 3010
dependencies:
  profile:
    name: 'profile'
    transport: Transport.TCP
    host: profile
    port: 3002
  chat_collector:
    name: 'chat-collector'
    transport: Transport.TCP
    host: chat-collector
    port: 3007
  prompt_proxy:
    name: 'prompt_proxy'
    transport: Transport.TCP
    host: prompt-proxy
    port: 3009
  telos_docs_service:
    name: 'telos_docs_service'
    transport: Transport.TCP
    host: telos-docs-service
    port: 3008
ai-enabled-apps:
  forgeofwill: The Forge of Will is a personal project management platform to allow users to plan, track, collaborate, and achieve their goals effectively. It combines task management, goal setting, and collaboration tools to help individuals and teams stay organized and productive.
toolSources:
  gateway: http://gateway:3000/api/mcp
models:
  workflow_control:
    name: 'llama3.2:3b'
    description: 'Fast model for detecting if a prompt requires tool calling'
    temperature: 0.3
    pullOnStartup: true
  tool_calling:
    name: 'llama3.2:3b'
    description: 'Model optimized for tool calling and function execution'
    temperature: 0.5
    pullOnStartup: true
  conversational:
    name: 'llama3.2:3b'
    description: 'Model for generating conversational responses'
    temperature: 0.7
    pullOnStartup: true
ollama:
  host: 192.168.50.14
  port: 11434
redis:
  host: redis
  port: 6379
