name: njsscan sarif
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  njsscan:
    runs-on: ubuntu-24.04
    name: njsscan code scanning
    permissions:
      security-events: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '. -c .njsscan --sarif --output results.sarif || true'
      - name: Upload njsscan report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
